// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: subscription.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	DurationDays  int32                  `protobuf:"varint,6,opt,name=durationDays,proto3" json:"durationDays,omitempty"` // 持续天数
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`                  // free, pro, enterprise
	AppId         string                 `protobuf:"bytes,8,opt,name=appId,proto3" json:"appId,omitempty"`                // 应用ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Plan) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Plan) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *Plan) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Plan) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ListPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

type CreatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	DurationDays  int32                  `protobuf:"varint,5,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanRequest) Reset() {
	*x = CreatePlanRequest{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanRequest) ProtoMessage() {}

func (x *CreatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanRequest.ProtoReflect.Descriptor instead.
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePlanRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreatePlanRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePlanRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *CreatePlanRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreatePlanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanReply) Reset() {
	*x = CreatePlanReply{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanReply) ProtoMessage() {}

func (x *CreatePlanReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanReply.ProtoReflect.Descriptor instead.
func (*CreatePlanReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePlanReply) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type UpdatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	DurationDays  int32                  `protobuf:"varint,6,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanRequest) Reset() {
	*x = UpdatePlanRequest{}
	mi := &file_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanRequest) ProtoMessage() {}

func (x *UpdatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePlanRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *UpdatePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePlanRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdatePlanRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdatePlanRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *UpdatePlanRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UpdatePlanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanReply) Reset() {
	*x = UpdatePlanReply{}
	mi := &file_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanReply) ProtoMessage() {}

func (x *UpdatePlanReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanReply.ProtoReflect.Descriptor instead.
func (*UpdatePlanReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePlanReply) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type DeletePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanRequest) Reset() {
	*x = DeletePlanRequest{}
	mi := &file_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanRequest) ProtoMessage() {}

func (x *DeletePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanRequest.ProtoReflect.Descriptor instead.
func (*DeletePlanRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePlanRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type DeletePlanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty"` // 被删除的套餐ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanReply) Reset() {
	*x = DeletePlanReply{}
	mi := &file_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanReply) ProtoMessage() {}

func (x *DeletePlanReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanReply.ProtoReflect.Descriptor instead.
func (*DeletePlanReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePlanReply) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type ListPlansReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*Plan                `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansReply) Reset() {
	*x = ListPlansReply{}
	mi := &file_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansReply) ProtoMessage() {}

func (x *ListPlansReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansReply.ProtoReflect.Descriptor instead.
func (*ListPlansReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *ListPlansReply) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type GetMySubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySubscriptionRequest) Reset() {
	*x = GetMySubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySubscriptionRequest) ProtoMessage() {}

func (x *GetMySubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetMySubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *GetMySubscriptionRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetMySubscriptionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=isActive,proto3" json:"isActive,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=planId,proto3" json:"planId,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`        // active, expired, paused, cancelled
	AutoRenew     bool                   `protobuf:"varint,6,opt,name=autoRenew,proto3" json:"autoRenew,omitempty"` // 是否自动续费
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySubscriptionReply) Reset() {
	*x = GetMySubscriptionReply{}
	mi := &file_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySubscriptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySubscriptionReply) ProtoMessage() {}

func (x *GetMySubscriptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySubscriptionReply.ProtoReflect.Descriptor instead.
func (*GetMySubscriptionReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *GetMySubscriptionReply) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetMySubscriptionReply) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *GetMySubscriptionReply) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetMySubscriptionReply) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetMySubscriptionReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMySubscriptionReply) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

type CreateSubscriptionOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=planId,proto3" json:"planId,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"` // alipay, wechatpay
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`               // 区域代码 (e.g., "CN", "US", "EU")，可选，默认 "default"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionOrderRequest) Reset() {
	*x = CreateSubscriptionOrderRequest{}
	mi := &file_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionOrderRequest) ProtoMessage() {}

func (x *CreateSubscriptionOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionOrderRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSubscriptionOrderRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateSubscriptionOrderRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateSubscriptionOrderRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateSubscriptionOrderRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type CreateSubscriptionOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`     // 业务订单号
	PaymentId     string                 `protobuf:"bytes,2,opt,name=paymentId,proto3" json:"paymentId,omitempty"` // 支付流水号
	PayUrl        string                 `protobuf:"bytes,3,opt,name=payUrl,proto3" json:"payUrl,omitempty"`
	PayCode       string                 `protobuf:"bytes,4,opt,name=payCode,proto3" json:"payCode,omitempty"`
	PayParams     string                 `protobuf:"bytes,5,opt,name=payParams,proto3" json:"payParams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionOrderReply) Reset() {
	*x = CreateSubscriptionOrderReply{}
	mi := &file_subscription_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionOrderReply) ProtoMessage() {}

func (x *CreateSubscriptionOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionOrderReply.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionOrderReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSubscriptionOrderReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPayCode() string {
	if x != nil {
		return x.PayCode
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPayParams() string {
	if x != nil {
		return x.PayParams
	}
	return ""
}

type HandlePaymentSuccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePaymentSuccessRequest) Reset() {
	*x = HandlePaymentSuccessRequest{}
	mi := &file_subscription_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePaymentSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePaymentSuccessRequest) ProtoMessage() {}

func (x *HandlePaymentSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePaymentSuccessRequest.ProtoReflect.Descriptor instead.
func (*HandlePaymentSuccessRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{13}
}

func (x *HandlePaymentSuccessRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *HandlePaymentSuccessRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *HandlePaymentSuccessRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 取消订阅
type CancelSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 取消原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{14}
}

func (x *CancelSubscriptionRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CancelSubscriptionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 暂停订阅
type PauseSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 暂停原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSubscriptionRequest) Reset() {
	*x = PauseSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSubscriptionRequest) ProtoMessage() {}

func (x *PauseSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*PauseSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{15}
}

func (x *PauseSubscriptionRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PauseSubscriptionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 恢复订阅
type ResumeSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSubscriptionRequest) Reset() {
	*x = ResumeSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSubscriptionRequest) ProtoMessage() {}

func (x *ResumeSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ResumeSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeSubscriptionRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 订阅历史记录
type SubscriptionHistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=planId,proto3" json:"planId,omitempty"`
	PlanName      string                 `protobuf:"bytes,3,opt,name=planName,proto3" json:"planName,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // active, expired, paused, cancelled
	Action        string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"` // created, renewed, upgraded, paused, resumed, cancelled
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionHistoryItem) Reset() {
	*x = SubscriptionHistoryItem{}
	mi := &file_subscription_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionHistoryItem) ProtoMessage() {}

func (x *SubscriptionHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionHistoryItem.ProtoReflect.Descriptor instead.
func (*SubscriptionHistoryItem) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{17}
}

func (x *SubscriptionHistoryItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubscriptionHistoryItem) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SubscriptionHistoryItem) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *SubscriptionHistoryItem) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SubscriptionHistoryItem) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SubscriptionHistoryItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubscriptionHistoryItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SubscriptionHistoryItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetSubscriptionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`         // 页码，从1开始
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 每页数量，默认10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionHistoryRequest) Reset() {
	*x = GetSubscriptionHistoryRequest{}
	mi := &file_subscription_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionHistoryRequest) ProtoMessage() {}

func (x *GetSubscriptionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{18}
}

func (x *GetSubscriptionHistoryRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetSubscriptionHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSubscriptionHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetSubscriptionHistoryReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*SubscriptionHistoryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                      `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                      `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionHistoryReply) Reset() {
	*x = GetSubscriptionHistoryReply{}
	mi := &file_subscription_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionHistoryReply) ProtoMessage() {}

func (x *GetSubscriptionHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionHistoryReply.ProtoReflect.Descriptor instead.
func (*GetSubscriptionHistoryReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{19}
}

func (x *GetSubscriptionHistoryReply) GetItems() []*SubscriptionHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetSubscriptionHistoryReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetSubscriptionHistoryReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSubscriptionHistoryReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 自动续费设置
type SetAutoRenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AutoRenew     bool                   `protobuf:"varint,2,opt,name=autoRenew,proto3" json:"autoRenew,omitempty"` // true: 开启自动续费, false: 关闭自动续费
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoRenewRequest) Reset() {
	*x = SetAutoRenewRequest{}
	mi := &file_subscription_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoRenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoRenewRequest) ProtoMessage() {}

func (x *SetAutoRenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoRenewRequest.ProtoReflect.Descriptor instead.
func (*SetAutoRenewRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{20}
}

func (x *SetAutoRenewRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SetAutoRenewRequest) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

// 获取即将过期的订阅
type GetExpiringSubscriptionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DaysBeforeExpiry int32                  `protobuf:"varint,1,opt,name=daysBeforeExpiry,proto3" json:"daysBeforeExpiry,omitempty"` // 过期前多少天，默认7天
	Page             int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，从1开始
	PageSize         int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`                 // 每页数量，默认10
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetExpiringSubscriptionsRequest) Reset() {
	*x = GetExpiringSubscriptionsRequest{}
	mi := &file_subscription_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpiringSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpiringSubscriptionsRequest) ProtoMessage() {}

func (x *GetExpiringSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpiringSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetExpiringSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{21}
}

func (x *GetExpiringSubscriptionsRequest) GetDaysBeforeExpiry() int32 {
	if x != nil {
		return x.DaysBeforeExpiry
	}
	return 0
}

func (x *GetExpiringSubscriptionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExpiringSubscriptionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SubscriptionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=planId,proto3" json:"planId,omitempty"`
	PlanName      string                 `protobuf:"bytes,3,opt,name=planName,proto3" json:"planName,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
	AutoRenew     bool                   `protobuf:"varint,6,opt,name=autoRenew,proto3" json:"autoRenew,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionInfo) Reset() {
	*x = SubscriptionInfo{}
	mi := &file_subscription_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionInfo) ProtoMessage() {}

func (x *SubscriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionInfo.ProtoReflect.Descriptor instead.
func (*SubscriptionInfo) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{22}
}

func (x *SubscriptionInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SubscriptionInfo) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SubscriptionInfo) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *SubscriptionInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SubscriptionInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SubscriptionInfo) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

func (x *SubscriptionInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetExpiringSubscriptionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*SubscriptionInfo    `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpiringSubscriptionsReply) Reset() {
	*x = GetExpiringSubscriptionsReply{}
	mi := &file_subscription_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpiringSubscriptionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpiringSubscriptionsReply) ProtoMessage() {}

func (x *GetExpiringSubscriptionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpiringSubscriptionsReply.ProtoReflect.Descriptor instead.
func (*GetExpiringSubscriptionsReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{23}
}

func (x *GetExpiringSubscriptionsReply) GetSubscriptions() []*SubscriptionInfo {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *GetExpiringSubscriptionsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetExpiringSubscriptionsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExpiringSubscriptionsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 批量更新过期订阅
type UpdateExpiredSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpiredSubscriptionsRequest) Reset() {
	*x = UpdateExpiredSubscriptionsRequest{}
	mi := &file_subscription_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpiredSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpiredSubscriptionsRequest) ProtoMessage() {}

func (x *UpdateExpiredSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpiredSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpiredSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{24}
}

type UpdateExpiredSubscriptionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updatedCount,proto3" json:"updatedCount,omitempty"`
	UpdatedUids   []uint64               `protobuf:"varint,2,rep,packed,name=updatedUids,proto3" json:"updatedUids,omitempty"` // 更新的用户ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpiredSubscriptionsReply) Reset() {
	*x = UpdateExpiredSubscriptionsReply{}
	mi := &file_subscription_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpiredSubscriptionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpiredSubscriptionsReply) ProtoMessage() {}

func (x *UpdateExpiredSubscriptionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpiredSubscriptionsReply.ProtoReflect.Descriptor instead.
func (*UpdateExpiredSubscriptionsReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateExpiredSubscriptionsReply) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *UpdateExpiredSubscriptionsReply) GetUpdatedUids() []uint64 {
	if x != nil {
		return x.UpdatedUids
	}
	return nil
}

// 自动续费处理
type ProcessAutoRenewalsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DaysBeforeExpiry int32                  `protobuf:"varint,1,opt,name=daysBeforeExpiry,proto3" json:"daysBeforeExpiry,omitempty"` // 提前多少天续费，默认3天
	DryRun           bool                   `protobuf:"varint,2,opt,name=dryRun,proto3" json:"dryRun,omitempty"`                     // 是否为测试运行
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessAutoRenewalsRequest) Reset() {
	*x = ProcessAutoRenewalsRequest{}
	mi := &file_subscription_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAutoRenewalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAutoRenewalsRequest) ProtoMessage() {}

func (x *ProcessAutoRenewalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAutoRenewalsRequest.ProtoReflect.Descriptor instead.
func (*ProcessAutoRenewalsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{26}
}

func (x *ProcessAutoRenewalsRequest) GetDaysBeforeExpiry() int32 {
	if x != nil {
		return x.DaysBeforeExpiry
	}
	return 0
}

func (x *ProcessAutoRenewalsRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type AutoRenewResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=planId,proto3" json:"planId,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	OrderId       string                 `protobuf:"bytes,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	PaymentId     string                 `protobuf:"bytes,5,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoRenewResult) Reset() {
	*x = AutoRenewResult{}
	mi := &file_subscription_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoRenewResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoRenewResult) ProtoMessage() {}

func (x *AutoRenewResult) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoRenewResult.ProtoReflect.Descriptor instead.
func (*AutoRenewResult) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{27}
}

func (x *AutoRenewResult) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AutoRenewResult) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *AutoRenewResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AutoRenewResult) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AutoRenewResult) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *AutoRenewResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ProcessAutoRenewalsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int32                  `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`     // 总共需要处理的数量
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=successCount,proto3" json:"successCount,omitempty"` // 成功的数量
	FailedCount   int32                  `protobuf:"varint,3,opt,name=failedCount,proto3" json:"failedCount,omitempty"`   // 失败的数量
	Results       []*AutoRenewResult     `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessAutoRenewalsReply) Reset() {
	*x = ProcessAutoRenewalsReply{}
	mi := &file_subscription_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAutoRenewalsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAutoRenewalsReply) ProtoMessage() {}

func (x *ProcessAutoRenewalsReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAutoRenewalsReply.ProtoReflect.Descriptor instead.
func (*ProcessAutoRenewalsReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{28}
}

func (x *ProcessAutoRenewalsReply) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ProcessAutoRenewalsReply) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ProcessAutoRenewalsReply) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *ProcessAutoRenewalsReply) GetResults() []*AutoRenewResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 区域定价相关消息
type PlanPricing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanPricingId uint64                 `protobuf:"varint,1,opt,name=planPricingId,proto3" json:"planPricingId,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=planId,proto3" json:"planId,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=countryCode,proto3" json:"countryCode,omitempty"` // ISO 3166-1 alpha-2 国家代码
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanPricing) Reset() {
	*x = PlanPricing{}
	mi := &file_subscription_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanPricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanPricing) ProtoMessage() {}

func (x *PlanPricing) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanPricing.ProtoReflect.Descriptor instead.
func (*PlanPricing) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{29}
}

func (x *PlanPricing) GetPlanPricingId() uint64 {
	if x != nil {
		return x.PlanPricingId
	}
	return 0
}

func (x *PlanPricing) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanPricing) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *PlanPricing) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PlanPricing) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ListPlanPricingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlanPricingsRequest) Reset() {
	*x = ListPlanPricingsRequest{}
	mi := &file_subscription_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlanPricingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlanPricingsRequest) ProtoMessage() {}

func (x *ListPlanPricingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlanPricingsRequest.ProtoReflect.Descriptor instead.
func (*ListPlanPricingsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{30}
}

func (x *ListPlanPricingsRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type ListPlanPricingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pricings      []*PlanPricing         `protobuf:"bytes,1,rep,name=pricings,proto3" json:"pricings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlanPricingsReply) Reset() {
	*x = ListPlanPricingsReply{}
	mi := &file_subscription_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlanPricingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlanPricingsReply) ProtoMessage() {}

func (x *ListPlanPricingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlanPricingsReply.ProtoReflect.Descriptor instead.
func (*ListPlanPricingsReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{31}
}

func (x *ListPlanPricingsReply) GetPricings() []*PlanPricing {
	if x != nil {
		return x.Pricings
	}
	return nil
}

type CreatePlanPricingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty"`
	CountryCode   string                 `protobuf:"bytes,2,opt,name=countryCode,proto3" json:"countryCode,omitempty"` // ISO 3166-1 alpha-2
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanPricingRequest) Reset() {
	*x = CreatePlanPricingRequest{}
	mi := &file_subscription_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanPricingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanPricingRequest) ProtoMessage() {}

func (x *CreatePlanPricingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanPricingRequest.ProtoReflect.Descriptor instead.
func (*CreatePlanPricingRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{32}
}

func (x *CreatePlanPricingRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreatePlanPricingRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CreatePlanPricingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreatePlanPricingRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreatePlanPricingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pricing       *PlanPricing           `protobuf:"bytes,1,opt,name=pricing,proto3" json:"pricing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanPricingReply) Reset() {
	*x = CreatePlanPricingReply{}
	mi := &file_subscription_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanPricingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanPricingReply) ProtoMessage() {}

func (x *CreatePlanPricingReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanPricingReply.ProtoReflect.Descriptor instead.
func (*CreatePlanPricingReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{33}
}

func (x *CreatePlanPricingReply) GetPricing() *PlanPricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

type UpdatePlanPricingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanPricingId uint64                 `protobuf:"varint,1,opt,name=planPricingId,proto3" json:"planPricingId,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanPricingRequest) Reset() {
	*x = UpdatePlanPricingRequest{}
	mi := &file_subscription_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanPricingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanPricingRequest) ProtoMessage() {}

func (x *UpdatePlanPricingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanPricingRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlanPricingRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{34}
}

func (x *UpdatePlanPricingRequest) GetPlanPricingId() uint64 {
	if x != nil {
		return x.PlanPricingId
	}
	return 0
}

func (x *UpdatePlanPricingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdatePlanPricingRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type UpdatePlanPricingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pricing       *PlanPricing           `protobuf:"bytes,1,opt,name=pricing,proto3" json:"pricing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanPricingReply) Reset() {
	*x = UpdatePlanPricingReply{}
	mi := &file_subscription_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanPricingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanPricingReply) ProtoMessage() {}

func (x *UpdatePlanPricingReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanPricingReply.ProtoReflect.Descriptor instead.
func (*UpdatePlanPricingReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{35}
}

func (x *UpdatePlanPricingReply) GetPricing() *PlanPricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

type DeletePlanPricingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanPricingId uint64                 `protobuf:"varint,1,opt,name=planPricingId,proto3" json:"planPricingId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanPricingRequest) Reset() {
	*x = DeletePlanPricingRequest{}
	mi := &file_subscription_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanPricingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanPricingRequest) ProtoMessage() {}

func (x *DeletePlanPricingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanPricingRequest.ProtoReflect.Descriptor instead.
func (*DeletePlanPricingRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{36}
}

func (x *DeletePlanPricingRequest) GetPlanPricingId() uint64 {
	if x != nil {
		return x.PlanPricingId
	}
	return 0
}

type DeletePlanPricingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanPricingId uint64                 `protobuf:"varint,1,opt,name=planPricingId,proto3" json:"planPricingId,omitempty"` // 被删除的区域定价ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanPricingReply) Reset() {
	*x = DeletePlanPricingReply{}
	mi := &file_subscription_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanPricingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanPricingReply) ProtoMessage() {}

func (x *DeletePlanPricingReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanPricingReply.ProtoReflect.Descriptor instead.
func (*DeletePlanPricingReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{37}
}

func (x *DeletePlanPricingReply) GetPlanPricingId() uint64 {
	if x != nil {
		return x.PlanPricingId
	}
	return 0
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\x0fsubscription.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd4\x01\n" +
	"\x04Plan\x12\x16\n" +
	"\x06planId\x18\x01 \x01(\tR\x06planId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\"\n" +
	"\fdurationDays\x18\x06 \x01(\x05R\fdurationDays\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x14\n" +
	"\x05appId\x18\b \x01(\tR\x05appId\"\x12\n" +
	"\x10ListPlansRequest\"\xea\x01\n" +
	"\x11CreatePlanRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12$\n" +
	"\x05price\x18\x03 \x01(\x01B\x0e\xfaB\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\x05price\x12$\n" +
	"\bcurrency\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\bcurrency\x12+\n" +
	"\fdurationDays\x18\x05 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\fdurationDays\x12\x1b\n" +
	"\x04type\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04type\"<\n" +
	"\x0fCreatePlanReply\x12)\n" +
	"\x04plan\x18\x01 \x01(\v2\x15.subscription.v1.PlanR\x04plan\"\xd4\x01\n" +
	"\x11UpdatePlanRequest\x12\x1f\n" +
	"\x06planId\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06planId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\"\n" +
	"\fdurationDays\x18\x06 \x01(\x05R\fdurationDays\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\"<\n" +
	"\x0fUpdatePlanReply\x12)\n" +
	"\x04plan\x18\x01 \x01(\v2\x15.subscription.v1.PlanR\x04plan\"4\n" +
	"\x11DeletePlanRequest\x12\x1f\n" +
	"\x06planId\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06planId\")\n" +
	"\x0fDeletePlanReply\x12\x16\n" +
	"\x06planId\x18\x01 \x01(\tR\x06planId\"=\n" +
	"\x0eListPlansReply\x12+\n" +
	"\x05plans\x18\x01 \x03(\v2\x15.subscription.v1.PlanR\x05plans\"5\n" +
	"\x18GetMySubscriptionRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\"\xba\x01\n" +
	"\x16GetMySubscriptionReply\x12\x1a\n" +
	"\bisActive\x18\x01 \x01(\bR\bisActive\x12\x16\n" +
	"\x06planId\x18\x02 \x01(\tR\x06planId\x12\x1c\n" +
	"\tstartTime\x18\x03 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x04 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\tautoRenew\x18\x06 \x01(\bR\tautoRenew\"\xb6\x01\n" +
	"\x1eCreateSubscriptionOrderRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\x12!\n" +
	"\x06planId\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x06planId\x12>\n" +
	"\rpaymentMethod\x18\x03 \x01(\tB\x18\xfaB\x15r\x13R\x06alipayR\twechatpayR\rpaymentMethod\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\"\xa6\x01\n" +
	"\x1cCreateSubscriptionOrderReply\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\x12\x1c\n" +
	"\tpaymentId\x18\x02 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06payUrl\x18\x03 \x01(\tR\x06payUrl\x12\x18\n" +
	"\apayCode\x18\x04 \x01(\tR\apayCode\x12\x1c\n" +
	"\tpayParams\x18\x05 \x01(\tR\tpayParams\"\x93\x01\n" +
	"\x1bHandlePaymentSuccessRequest\x12#\n" +
	"\aorderId\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\aorderId\x12'\n" +
	"\tpaymentId\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\tpaymentId\x12&\n" +
	"\x06amount\x18\x03 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x06amount\"N\n" +
	"\x19CancelSubscriptionRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"M\n" +
	"\x18PauseSubscriptionRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"6\n" +
	"\x19ResumeSubscriptionRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\"\xe3\x01\n" +
	"\x17SubscriptionHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06planId\x18\x02 \x01(\tR\x06planId\x12\x1a\n" +
	"\bplanName\x18\x03 \x01(\tR\bplanName\x12\x1c\n" +
	"\tstartTime\x18\x04 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x05 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\x03R\tcreatedAt\"j\n" +
	"\x1dGetSubscriptionHistoryRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"\xa3\x01\n" +
	"\x1bGetSubscriptionHistoryReply\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.subscription.v1.SubscriptionHistoryItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\"N\n" +
	"\x13SetAutoRenewRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\x12\x1c\n" +
	"\tautoRenew\x18\x02 \x01(\bR\tautoRenew\"\x88\x01\n" +
	"\x1fGetExpiringSubscriptionsRequest\x125\n" +
	"\x10daysBeforeExpiry\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x1e(\x01R\x10daysBeforeExpiry\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"\xc6\x01\n" +
	"\x10SubscriptionInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x16\n" +
	"\x06planId\x18\x02 \x01(\tR\x06planId\x12\x1a\n" +
	"\bplanName\x18\x03 \x01(\tR\bplanName\x12\x1c\n" +
	"\tstartTime\x18\x04 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x05 \x01(\x03R\aendTime\x12\x1c\n" +
	"\tautoRenew\x18\x06 \x01(\bR\tautoRenew\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\"\xae\x01\n" +
	"\x1dGetExpiringSubscriptionsReply\x12G\n" +
	"\rsubscriptions\x18\x01 \x03(\v2!.subscription.v1.SubscriptionInfoR\rsubscriptions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\"#\n" +
	"!UpdateExpiredSubscriptionsRequest\"g\n" +
	"\x1fUpdateExpiredSubscriptionsReply\x12\"\n" +
	"\fupdatedCount\x18\x01 \x01(\x05R\fupdatedCount\x12 \n" +
	"\vupdatedUids\x18\x02 \x03(\x04R\vupdatedUids\"k\n" +
	"\x1aProcessAutoRenewalsRequest\x125\n" +
	"\x10daysBeforeExpiry\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x1e(\x01R\x10daysBeforeExpiry\x12\x16\n" +
	"\x06dryRun\x18\x02 \x01(\bR\x06dryRun\"\xb1\x01\n" +
	"\x0fAutoRenewResult\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x16\n" +
	"\x06planId\x18\x02 \x01(\tR\x06planId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\aorderId\x18\x04 \x01(\tR\aorderId\x12\x1c\n" +
	"\tpaymentId\x18\x05 \x01(\tR\tpaymentId\x12\"\n" +
	"\ferrorMessage\x18\x06 \x01(\tR\ferrorMessage\"\xbc\x01\n" +
	"\x18ProcessAutoRenewalsReply\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x05R\n" +
	"totalCount\x12\"\n" +
	"\fsuccessCount\x18\x02 \x01(\x05R\fsuccessCount\x12 \n" +
	"\vfailedCount\x18\x03 \x01(\x05R\vfailedCount\x12:\n" +
	"\aresults\x18\x04 \x03(\v2 .subscription.v1.AutoRenewResultR\aresults\"\x9f\x01\n" +
	"\vPlanPricing\x12$\n" +
	"\rplanPricingId\x18\x01 \x01(\x04R\rplanPricingId\x12\x16\n" +
	"\x06planId\x18\x02 \x01(\tR\x06planId\x12 \n" +
	"\vcountryCode\x18\x03 \x01(\tR\vcountryCode\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\":\n" +
	"\x17ListPlanPricingsRequest\x12\x1f\n" +
	"\x06planId\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06planId\"Q\n" +
	"\x15ListPlanPricingsReply\x128\n" +
	"\bpricings\x18\x01 \x03(\v2\x1c.subscription.v1.PlanPricingR\bpricings\"\xb3\x01\n" +
	"\x18CreatePlanPricingRequest\x12\x1f\n" +
	"\x06planId\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06planId\x12*\n" +
	"\vcountryCode\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x02R\vcountryCode\x12$\n" +
	"\x05price\x18\x03 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x05price\x12$\n" +
	"\bcurrency\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\bcurrency\"P\n" +
	"\x16CreatePlanPricingReply\x126\n" +
	"\apricing\x18\x01 \x01(\v2\x1c.subscription.v1.PlanPricingR\apricing\"\x95\x01\n" +
	"\x18UpdatePlanPricingRequest\x12-\n" +
	"\rplanPricingId\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\rplanPricingId\x12$\n" +
	"\x05price\x18\x02 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x05price\x12$\n" +
	"\bcurrency\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\bcurrency\"P\n" +
	"\x16UpdatePlanPricingReply\x126\n" +
	"\apricing\x18\x01 \x01(\v2\x1c.subscription.v1.PlanPricingR\apricing\"I\n" +
	"\x18DeletePlanPricingRequest\x12-\n" +
	"\rplanPricingId\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\rplanPricingId\">\n" +
	"\x16DeletePlanPricingReply\x12$\n" +
	"\rplanPricingId\x18\x01 \x01(\x04R\rplanPricingId2\xa1\x15\n" +
	"\fSubscription\x12o\n" +
	"\tListPlans\x12!.subscription.v1.ListPlansRequest\x1a\x1f.subscription.v1.ListPlansReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/subscription/plans\x12\x8a\x01\n" +
	"\x11GetMySubscription\x12).subscription.v1.GetMySubscriptionRequest\x1a'.subscription.v1.GetMySubscriptionReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/subscription/my/{uid}\x12\x9c\x01\n" +
	"\x17CreateSubscriptionOrder\x12/.subscription.v1.CreateSubscriptionOrderRequest\x1a-.subscription.v1.CreateSubscriptionOrderReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/subscription/order\x12\x89\x01\n" +
	"\x14HandlePaymentSuccess\x12,.subscription.v1.HandlePaymentSuccessRequest\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/subscription/payment/success\x12|\n" +
	"\x12CancelSubscription\x12*.subscription.v1.CancelSubscriptionRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/subscription/cancel\x12y\n" +
	"\x11PauseSubscription\x12).subscription.v1.PauseSubscriptionRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/subscription/pause\x12|\n" +
	"\x12ResumeSubscription\x12*.subscription.v1.ResumeSubscriptionRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/subscription/resume\x12\x9e\x01\n" +
	"\x16GetSubscriptionHistory\x12..subscription.v1.GetSubscriptionHistoryRequest\x1a,.subscription.v1.GetSubscriptionHistoryReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/subscription/history/{uid}\x12t\n" +
	"\fSetAutoRenew\x12$.subscription.v1.SetAutoRenewRequest\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/subscription/auto-renew\x12\x9f\x01\n" +
	"\x18GetExpiringSubscriptions\x120.subscription.v1.GetExpiringSubscriptionsRequest\x1a..subscription.v1.GetExpiringSubscriptionsReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/subscription/expiring\x12\xae\x01\n" +
	"\x1aUpdateExpiredSubscriptions\x122.subscription.v1.UpdateExpiredSubscriptionsRequest\x1a0.subscription.v1.UpdateExpiredSubscriptionsReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/subscription/expired/update\x12\x9d\x01\n" +
	"\x13ProcessAutoRenewals\x12+.subscription.v1.ProcessAutoRenewalsRequest\x1a).subscription.v1.ProcessAutoRenewalsReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/subscription/auto-renew/process\x12u\n" +
	"\n" +
	"CreatePlan\x12\".subscription.v1.CreatePlanRequest\x1a .subscription.v1.CreatePlanReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/subscription/plans\x12~\n" +
	"\n" +
	"UpdatePlan\x12\".subscription.v1.UpdatePlanRequest\x1a .subscription.v1.UpdatePlanReply\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/v1/subscription/plans/{planId}\x12{\n" +
	"\n" +
	"DeletePlan\x12\".subscription.v1.DeletePlanRequest\x1a .subscription.v1.DeletePlanReply\"'\x82\xd3\xe4\x93\x02!*\x1f/v1/subscription/plans/{planId}\x12\x96\x01\n" +
	"\x10ListPlanPricings\x12(.subscription.v1.ListPlanPricingsRequest\x1a&.subscription.v1.ListPlanPricingsReply\"0\x82\xd3\xe4\x93\x02*\x12(/v1/subscription/plans/{planId}/pricings\x12\x9c\x01\n" +
	"\x11CreatePlanPricing\x12).subscription.v1.CreatePlanPricingRequest\x1a'.subscription.v1.CreatePlanPricingReply\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/subscription/plans/{planId}/pricings\x12\x9d\x01\n" +
	"\x11UpdatePlanPricing\x12).subscription.v1.UpdatePlanPricingRequest\x1a'.subscription.v1.UpdatePlanPricingReply\"4\x82\xd3\xe4\x93\x02.:\x01*\x1a)/v1/subscription/pricings/{planPricingId}\x12\x9a\x01\n" +
	"\x11DeletePlanPricing\x12).subscription.v1.DeletePlanPricingRequest\x1a'.subscription.v1.DeletePlanPricingReply\"1\x82\xd3\xe4\x93\x02+*)/v1/subscription/pricings/{planPricingId}B:Z8xinyuan_tech/subscription-service/api/subscription/v1;v1b\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_subscription_proto_goTypes = []any{
	(*Plan)(nil),                              // 0: subscription.v1.Plan
	(*ListPlansRequest)(nil),                  // 1: subscription.v1.ListPlansRequest
	(*CreatePlanRequest)(nil),                 // 2: subscription.v1.CreatePlanRequest
	(*CreatePlanReply)(nil),                   // 3: subscription.v1.CreatePlanReply
	(*UpdatePlanRequest)(nil),                 // 4: subscription.v1.UpdatePlanRequest
	(*UpdatePlanReply)(nil),                   // 5: subscription.v1.UpdatePlanReply
	(*DeletePlanRequest)(nil),                 // 6: subscription.v1.DeletePlanRequest
	(*DeletePlanReply)(nil),                   // 7: subscription.v1.DeletePlanReply
	(*ListPlansReply)(nil),                    // 8: subscription.v1.ListPlansReply
	(*GetMySubscriptionRequest)(nil),          // 9: subscription.v1.GetMySubscriptionRequest
	(*GetMySubscriptionReply)(nil),            // 10: subscription.v1.GetMySubscriptionReply
	(*CreateSubscriptionOrderRequest)(nil),    // 11: subscription.v1.CreateSubscriptionOrderRequest
	(*CreateSubscriptionOrderReply)(nil),      // 12: subscription.v1.CreateSubscriptionOrderReply
	(*HandlePaymentSuccessRequest)(nil),       // 13: subscription.v1.HandlePaymentSuccessRequest
	(*CancelSubscriptionRequest)(nil),         // 14: subscription.v1.CancelSubscriptionRequest
	(*PauseSubscriptionRequest)(nil),          // 15: subscription.v1.PauseSubscriptionRequest
	(*ResumeSubscriptionRequest)(nil),         // 16: subscription.v1.ResumeSubscriptionRequest
	(*SubscriptionHistoryItem)(nil),           // 17: subscription.v1.SubscriptionHistoryItem
	(*GetSubscriptionHistoryRequest)(nil),     // 18: subscription.v1.GetSubscriptionHistoryRequest
	(*GetSubscriptionHistoryReply)(nil),       // 19: subscription.v1.GetSubscriptionHistoryReply
	(*SetAutoRenewRequest)(nil),               // 20: subscription.v1.SetAutoRenewRequest
	(*GetExpiringSubscriptionsRequest)(nil),   // 21: subscription.v1.GetExpiringSubscriptionsRequest
	(*SubscriptionInfo)(nil),                  // 22: subscription.v1.SubscriptionInfo
	(*GetExpiringSubscriptionsReply)(nil),     // 23: subscription.v1.GetExpiringSubscriptionsReply
	(*UpdateExpiredSubscriptionsRequest)(nil), // 24: subscription.v1.UpdateExpiredSubscriptionsRequest
	(*UpdateExpiredSubscriptionsReply)(nil),   // 25: subscription.v1.UpdateExpiredSubscriptionsReply
	(*ProcessAutoRenewalsRequest)(nil),        // 26: subscription.v1.ProcessAutoRenewalsRequest
	(*AutoRenewResult)(nil),                   // 27: subscription.v1.AutoRenewResult
	(*ProcessAutoRenewalsReply)(nil),          // 28: subscription.v1.ProcessAutoRenewalsReply
	(*PlanPricing)(nil),                       // 29: subscription.v1.PlanPricing
	(*ListPlanPricingsRequest)(nil),           // 30: subscription.v1.ListPlanPricingsRequest
	(*ListPlanPricingsReply)(nil),             // 31: subscription.v1.ListPlanPricingsReply
	(*CreatePlanPricingRequest)(nil),          // 32: subscription.v1.CreatePlanPricingRequest
	(*CreatePlanPricingReply)(nil),            // 33: subscription.v1.CreatePlanPricingReply
	(*UpdatePlanPricingRequest)(nil),          // 34: subscription.v1.UpdatePlanPricingRequest
	(*UpdatePlanPricingReply)(nil),            // 35: subscription.v1.UpdatePlanPricingReply
	(*DeletePlanPricingRequest)(nil),          // 36: subscription.v1.DeletePlanPricingRequest
	(*DeletePlanPricingReply)(nil),            // 37: subscription.v1.DeletePlanPricingReply
	(*emptypb.Empty)(nil),                     // 38: google.protobuf.Empty
}
var file_subscription_proto_depIdxs = []int32{
	0,  // 0: subscription.v1.CreatePlanReply.plan:type_name -> subscription.v1.Plan
	0,  // 1: subscription.v1.UpdatePlanReply.plan:type_name -> subscription.v1.Plan
	0,  // 2: subscription.v1.ListPlansReply.plans:type_name -> subscription.v1.Plan
	17, // 3: subscription.v1.GetSubscriptionHistoryReply.items:type_name -> subscription.v1.SubscriptionHistoryItem
	22, // 4: subscription.v1.GetExpiringSubscriptionsReply.subscriptions:type_name -> subscription.v1.SubscriptionInfo
	27, // 5: subscription.v1.ProcessAutoRenewalsReply.results:type_name -> subscription.v1.AutoRenewResult
	29, // 6: subscription.v1.ListPlanPricingsReply.pricings:type_name -> subscription.v1.PlanPricing
	29, // 7: subscription.v1.CreatePlanPricingReply.pricing:type_name -> subscription.v1.PlanPricing
	29, // 8: subscription.v1.UpdatePlanPricingReply.pricing:type_name -> subscription.v1.PlanPricing
	1,  // 9: subscription.v1.Subscription.ListPlans:input_type -> subscription.v1.ListPlansRequest
	9,  // 10: subscription.v1.Subscription.GetMySubscription:input_type -> subscription.v1.GetMySubscriptionRequest
	11, // 11: subscription.v1.Subscription.CreateSubscriptionOrder:input_type -> subscription.v1.CreateSubscriptionOrderRequest
	13, // 12: subscription.v1.Subscription.HandlePaymentSuccess:input_type -> subscription.v1.HandlePaymentSuccessRequest
	14, // 13: subscription.v1.Subscription.CancelSubscription:input_type -> subscription.v1.CancelSubscriptionRequest
	15, // 14: subscription.v1.Subscription.PauseSubscription:input_type -> subscription.v1.PauseSubscriptionRequest
	16, // 15: subscription.v1.Subscription.ResumeSubscription:input_type -> subscription.v1.ResumeSubscriptionRequest
	18, // 16: subscription.v1.Subscription.GetSubscriptionHistory:input_type -> subscription.v1.GetSubscriptionHistoryRequest
	20, // 17: subscription.v1.Subscription.SetAutoRenew:input_type -> subscription.v1.SetAutoRenewRequest
	21, // 18: subscription.v1.Subscription.GetExpiringSubscriptions:input_type -> subscription.v1.GetExpiringSubscriptionsRequest
	24, // 19: subscription.v1.Subscription.UpdateExpiredSubscriptions:input_type -> subscription.v1.UpdateExpiredSubscriptionsRequest
	26, // 20: subscription.v1.Subscription.ProcessAutoRenewals:input_type -> subscription.v1.ProcessAutoRenewalsRequest
	2,  // 21: subscription.v1.Subscription.CreatePlan:input_type -> subscription.v1.CreatePlanRequest
	4,  // 22: subscription.v1.Subscription.UpdatePlan:input_type -> subscription.v1.UpdatePlanRequest
	6,  // 23: subscription.v1.Subscription.DeletePlan:input_type -> subscription.v1.DeletePlanRequest
	30, // 24: subscription.v1.Subscription.ListPlanPricings:input_type -> subscription.v1.ListPlanPricingsRequest
	32, // 25: subscription.v1.Subscription.CreatePlanPricing:input_type -> subscription.v1.CreatePlanPricingRequest
	34, // 26: subscription.v1.Subscription.UpdatePlanPricing:input_type -> subscription.v1.UpdatePlanPricingRequest
	36, // 27: subscription.v1.Subscription.DeletePlanPricing:input_type -> subscription.v1.DeletePlanPricingRequest
	8,  // 28: subscription.v1.Subscription.ListPlans:output_type -> subscription.v1.ListPlansReply
	10, // 29: subscription.v1.Subscription.GetMySubscription:output_type -> subscription.v1.GetMySubscriptionReply
	12, // 30: subscription.v1.Subscription.CreateSubscriptionOrder:output_type -> subscription.v1.CreateSubscriptionOrderReply
	38, // 31: subscription.v1.Subscription.HandlePaymentSuccess:output_type -> google.protobuf.Empty
	38, // 32: subscription.v1.Subscription.CancelSubscription:output_type -> google.protobuf.Empty
	38, // 33: subscription.v1.Subscription.PauseSubscription:output_type -> google.protobuf.Empty
	38, // 34: subscription.v1.Subscription.ResumeSubscription:output_type -> google.protobuf.Empty
	19, // 35: subscription.v1.Subscription.GetSubscriptionHistory:output_type -> subscription.v1.GetSubscriptionHistoryReply
	38, // 36: subscription.v1.Subscription.SetAutoRenew:output_type -> google.protobuf.Empty
	23, // 37: subscription.v1.Subscription.GetExpiringSubscriptions:output_type -> subscription.v1.GetExpiringSubscriptionsReply
	25, // 38: subscription.v1.Subscription.UpdateExpiredSubscriptions:output_type -> subscription.v1.UpdateExpiredSubscriptionsReply
	28, // 39: subscription.v1.Subscription.ProcessAutoRenewals:output_type -> subscription.v1.ProcessAutoRenewalsReply
	3,  // 40: subscription.v1.Subscription.CreatePlan:output_type -> subscription.v1.CreatePlanReply
	5,  // 41: subscription.v1.Subscription.UpdatePlan:output_type -> subscription.v1.UpdatePlanReply
	7,  // 42: subscription.v1.Subscription.DeletePlan:output_type -> subscription.v1.DeletePlanReply
	31, // 43: subscription.v1.Subscription.ListPlanPricings:output_type -> subscription.v1.ListPlanPricingsReply
	33, // 44: subscription.v1.Subscription.CreatePlanPricing:output_type -> subscription.v1.CreatePlanPricingReply
	35, // 45: subscription.v1.Subscription.UpdatePlanPricing:output_type -> subscription.v1.UpdatePlanPricingReply
	37, // 46: subscription.v1.Subscription.DeletePlanPricing:output_type -> subscription.v1.DeletePlanPricingReply
	28, // [28:47] is the sub-list for method output_type
	9,  // [9:28] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
