// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/subscription/v1/subscription.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	DurationDays  int32                  `protobuf:"varint,6,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"` // 持续天数
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`                                      // free, pro, enterprise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_api_subscription_v1_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Plan) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Plan) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *Plan) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_api_subscription_v1_subscription_proto_rawDescGZIP(), []int{1}
}

type ListPlansReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*Plan                `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansReply) Reset() {
	*x = ListPlansReply{}
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansReply) ProtoMessage() {}

func (x *ListPlansReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansReply.ProtoReflect.Descriptor instead.
func (*ListPlansReply) Descriptor() ([]byte, []int) {
	return file_api_subscription_v1_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *ListPlansReply) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type GetMySubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySubscriptionRequest) Reset() {
	*x = GetMySubscriptionRequest{}
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySubscriptionRequest) ProtoMessage() {}

func (x *GetMySubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetMySubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_subscription_v1_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetMySubscriptionRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetMySubscriptionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // active, expired
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySubscriptionReply) Reset() {
	*x = GetMySubscriptionReply{}
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySubscriptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySubscriptionReply) ProtoMessage() {}

func (x *GetMySubscriptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySubscriptionReply.ProtoReflect.Descriptor instead.
func (*GetMySubscriptionReply) Descriptor() ([]byte, []int) {
	return file_api_subscription_v1_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *GetMySubscriptionReply) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetMySubscriptionReply) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *GetMySubscriptionReply) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetMySubscriptionReply) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetMySubscriptionReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateSubscriptionOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // alipay, wechatpay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionOrderRequest) Reset() {
	*x = CreateSubscriptionOrderRequest{}
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionOrderRequest) ProtoMessage() {}

func (x *CreateSubscriptionOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_subscription_v1_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSubscriptionOrderRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateSubscriptionOrderRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateSubscriptionOrderRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CreateSubscriptionOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`       // 业务订单号
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // 支付流水号
	PayUrl        string                 `protobuf:"bytes,3,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	PayCode       string                 `protobuf:"bytes,4,opt,name=pay_code,json=payCode,proto3" json:"pay_code,omitempty"`
	PayParams     string                 `protobuf:"bytes,5,opt,name=pay_params,json=payParams,proto3" json:"pay_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionOrderReply) Reset() {
	*x = CreateSubscriptionOrderReply{}
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionOrderReply) ProtoMessage() {}

func (x *CreateSubscriptionOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionOrderReply.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionOrderReply) Descriptor() ([]byte, []int) {
	return file_api_subscription_v1_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSubscriptionOrderReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPayCode() string {
	if x != nil {
		return x.PayCode
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPayParams() string {
	if x != nil {
		return x.PayParams
	}
	return ""
}

type HandlePaymentSuccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePaymentSuccessRequest) Reset() {
	*x = HandlePaymentSuccessRequest{}
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePaymentSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePaymentSuccessRequest) ProtoMessage() {}

func (x *HandlePaymentSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePaymentSuccessRequest.ProtoReflect.Descriptor instead.
func (*HandlePaymentSuccessRequest) Descriptor() ([]byte, []int) {
	return file_api_subscription_v1_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *HandlePaymentSuccessRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *HandlePaymentSuccessRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *HandlePaymentSuccessRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type HandlePaymentSuccessReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePaymentSuccessReply) Reset() {
	*x = HandlePaymentSuccessReply{}
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePaymentSuccessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePaymentSuccessReply) ProtoMessage() {}

func (x *HandlePaymentSuccessReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_v1_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePaymentSuccessReply.ProtoReflect.Descriptor instead.
func (*HandlePaymentSuccessReply) Descriptor() ([]byte, []int) {
	return file_api_subscription_v1_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *HandlePaymentSuccessReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_subscription_v1_subscription_proto protoreflect.FileDescriptor

const file_api_subscription_v1_subscription_proto_rawDesc = "" +
	"\n" +
	"&api/subscription/v1/subscription.proto\x12\x0fsubscription.v1\x1a\x1cgoogle/api/annotations.proto\"\xb7\x01\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12#\n" +
	"\rduration_days\x18\x06 \x01(\x05R\fdurationDays\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\"\x12\n" +
	"\x10ListPlansRequest\"=\n" +
	"\x0eListPlansReply\x12+\n" +
	"\x05plans\x18\x01 \x03(\v2\x15.subscription.v1.PlanR\x05plans\",\n" +
	"\x18GetMySubscriptionRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\"\xa0\x01\n" +
	"\x16GetMySubscriptionReply\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"r\n" +
	"\x1eCreateSubscriptionOrderRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\"\xab\x01\n" +
	"\x1cCreateSubscriptionOrderReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x17\n" +
	"\apay_url\x18\x03 \x01(\tR\x06payUrl\x12\x19\n" +
	"\bpay_code\x18\x04 \x01(\tR\apayCode\x12\x1d\n" +
	"\n" +
	"pay_params\x18\x05 \x01(\tR\tpayParams\"o\n" +
	"\x1bHandlePaymentSuccessRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"5\n" +
	"\x19HandlePaymentSuccessReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcb\x04\n" +
	"\fSubscription\x12o\n" +
	"\tListPlans\x12!.subscription.v1.ListPlansRequest\x1a\x1f.subscription.v1.ListPlansReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/subscription/plans\x12\x8a\x01\n" +
	"\x11GetMySubscription\x12).subscription.v1.GetMySubscriptionRequest\x1a'.subscription.v1.GetMySubscriptionReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/subscription/my/{uid}\x12\x9c\x01\n" +
	"\x17CreateSubscriptionOrder\x12/.subscription.v1.CreateSubscriptionOrderRequest\x1a-.subscription.v1.CreateSubscriptionOrderReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/subscription/order\x12\x9d\x01\n" +
	"\x14HandlePaymentSuccess\x12,.subscription.v1.HandlePaymentSuccessRequest\x1a*.subscription.v1.HandlePaymentSuccessReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/subscription/payment/successB:Z8xinyuan_tech/subscription-service/api/subscription/v1;v1b\x06proto3"

var (
	file_api_subscription_v1_subscription_proto_rawDescOnce sync.Once
	file_api_subscription_v1_subscription_proto_rawDescData []byte
)

func file_api_subscription_v1_subscription_proto_rawDescGZIP() []byte {
	file_api_subscription_v1_subscription_proto_rawDescOnce.Do(func() {
		file_api_subscription_v1_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_subscription_v1_subscription_proto_rawDesc), len(file_api_subscription_v1_subscription_proto_rawDesc)))
	})
	return file_api_subscription_v1_subscription_proto_rawDescData
}

var file_api_subscription_v1_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_subscription_v1_subscription_proto_goTypes = []any{
	(*Plan)(nil),                           // 0: subscription.v1.Plan
	(*ListPlansRequest)(nil),               // 1: subscription.v1.ListPlansRequest
	(*ListPlansReply)(nil),                 // 2: subscription.v1.ListPlansReply
	(*GetMySubscriptionRequest)(nil),       // 3: subscription.v1.GetMySubscriptionRequest
	(*GetMySubscriptionReply)(nil),         // 4: subscription.v1.GetMySubscriptionReply
	(*CreateSubscriptionOrderRequest)(nil), // 5: subscription.v1.CreateSubscriptionOrderRequest
	(*CreateSubscriptionOrderReply)(nil),   // 6: subscription.v1.CreateSubscriptionOrderReply
	(*HandlePaymentSuccessRequest)(nil),    // 7: subscription.v1.HandlePaymentSuccessRequest
	(*HandlePaymentSuccessReply)(nil),      // 8: subscription.v1.HandlePaymentSuccessReply
}
var file_api_subscription_v1_subscription_proto_depIdxs = []int32{
	0, // 0: subscription.v1.ListPlansReply.plans:type_name -> subscription.v1.Plan
	1, // 1: subscription.v1.Subscription.ListPlans:input_type -> subscription.v1.ListPlansRequest
	3, // 2: subscription.v1.Subscription.GetMySubscription:input_type -> subscription.v1.GetMySubscriptionRequest
	5, // 3: subscription.v1.Subscription.CreateSubscriptionOrder:input_type -> subscription.v1.CreateSubscriptionOrderRequest
	7, // 4: subscription.v1.Subscription.HandlePaymentSuccess:input_type -> subscription.v1.HandlePaymentSuccessRequest
	2, // 5: subscription.v1.Subscription.ListPlans:output_type -> subscription.v1.ListPlansReply
	4, // 6: subscription.v1.Subscription.GetMySubscription:output_type -> subscription.v1.GetMySubscriptionReply
	6, // 7: subscription.v1.Subscription.CreateSubscriptionOrder:output_type -> subscription.v1.CreateSubscriptionOrderReply
	8, // 8: subscription.v1.Subscription.HandlePaymentSuccess:output_type -> subscription.v1.HandlePaymentSuccessReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_subscription_v1_subscription_proto_init() }
func file_api_subscription_v1_subscription_proto_init() {
	if File_api_subscription_v1_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_subscription_v1_subscription_proto_rawDesc), len(file_api_subscription_v1_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_subscription_v1_subscription_proto_goTypes,
		DependencyIndexes: file_api_subscription_v1_subscription_proto_depIdxs,
		MessageInfos:      file_api_subscription_v1_subscription_proto_msgTypes,
	}.Build()
	File_api_subscription_v1_subscription_proto = out.File
	file_api_subscription_v1_subscription_proto_goTypes = nil
	file_api_subscription_v1_subscription_proto_depIdxs = nil
}
