// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: subscription.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSubscriptionCancelSubscription = "/subscription.v1.Subscription/CancelSubscription"
const OperationSubscriptionCreatePlan = "/subscription.v1.Subscription/CreatePlan"
const OperationSubscriptionCreatePlanPricing = "/subscription.v1.Subscription/CreatePlanPricing"
const OperationSubscriptionCreateSubscriptionOrder = "/subscription.v1.Subscription/CreateSubscriptionOrder"
const OperationSubscriptionDeletePlan = "/subscription.v1.Subscription/DeletePlan"
const OperationSubscriptionDeletePlanPricing = "/subscription.v1.Subscription/DeletePlanPricing"
const OperationSubscriptionEnsureDefaultFreeSubscription = "/subscription.v1.Subscription/EnsureDefaultFreeSubscription"
const OperationSubscriptionGetAppSubscriptionHistory = "/subscription.v1.Subscription/GetAppSubscriptionHistory"
const OperationSubscriptionGetExpiringSubscriptions = "/subscription.v1.Subscription/GetExpiringSubscriptions"
const OperationSubscriptionGetOrEnsureMySubscription = "/subscription.v1.Subscription/GetOrEnsureMySubscription"
const OperationSubscriptionGetSubscriptionHistory = "/subscription.v1.Subscription/GetSubscriptionHistory"
const OperationSubscriptionGetSubscriptionOrder = "/subscription.v1.Subscription/GetSubscriptionOrder"
const OperationSubscriptionHandlePaymentSuccess = "/subscription.v1.Subscription/HandlePaymentSuccess"
const OperationSubscriptionListAppSubscriptions = "/subscription.v1.Subscription/ListAppSubscriptions"
const OperationSubscriptionListPlanPricings = "/subscription.v1.Subscription/ListPlanPricings"
const OperationSubscriptionListPlans = "/subscription.v1.Subscription/ListPlans"
const OperationSubscriptionListSubscriptionOrders = "/subscription.v1.Subscription/ListSubscriptionOrders"
const OperationSubscriptionPauseSubscription = "/subscription.v1.Subscription/PauseSubscription"
const OperationSubscriptionProcessAutoRenewals = "/subscription.v1.Subscription/ProcessAutoRenewals"
const OperationSubscriptionResumeSubscription = "/subscription.v1.Subscription/ResumeSubscription"
const OperationSubscriptionSetAutoRenew = "/subscription.v1.Subscription/SetAutoRenew"
const OperationSubscriptionUpdateExpiredSubscriptions = "/subscription.v1.Subscription/UpdateExpiredSubscriptions"
const OperationSubscriptionUpdatePlan = "/subscription.v1.Subscription/UpdatePlan"
const OperationSubscriptionUpdatePlanPricing = "/subscription.v1.Subscription/UpdatePlanPricing"

type SubscriptionHTTPServer interface {
	// CancelSubscription 取消订阅
	CancelSubscription(context.Context, *CancelSubscriptionRequest) (*emptypb.Empty, error)
	// CreatePlan 创建订阅套餐
	CreatePlan(context.Context, *CreatePlanRequest) (*CreatePlanReply, error)
	// CreatePlanPricing 创建区域定价
	CreatePlanPricing(context.Context, *CreatePlanPricingRequest) (*CreatePlanPricingReply, error)
	// CreateSubscriptionOrder 创建订阅订单 (调用 Payment Service)
	CreateSubscriptionOrder(context.Context, *CreateSubscriptionOrderRequest) (*CreateSubscriptionOrderReply, error)
	// DeletePlan 删除订阅套餐（软删除：仅标记删除时间，数据保留；ListPlans 不再返回）
	DeletePlan(context.Context, *DeletePlanRequest) (*DeletePlanReply, error)
	// DeletePlanPricing 删除区域定价
	DeletePlanPricing(context.Context, *DeletePlanPricingRequest) (*DeletePlanPricingReply, error)
	// EnsureDefaultFreeSubscription 显式幂等开通默认免费档（与 GetOrEnsureMySubscription 内 Ensure 逻辑一致）。
	// 一般客户端只需 GET GetOrEnsure；本接口可用于显式「同步」或调试。
	EnsureDefaultFreeSubscription(context.Context, *EnsureDefaultFreeSubscriptionRequest) (*EnsureDefaultFreeSubscriptionReply, error)
	// GetAppSubscriptionHistory 获取应用的订阅历史记录（管理员视角）
	GetAppSubscriptionHistory(context.Context, *GetAppSubscriptionHistoryRequest) (*GetAppSubscriptionHistoryReply, error)
	// GetExpiringSubscriptions 获取即将过期的订阅（用于定时任务）
	GetExpiringSubscriptions(context.Context, *GetExpiringSubscriptionsRequest) (*GetExpiringSubscriptionsReply, error)
	// GetOrEnsureMySubscription 获取（并必要时初始化）当前用户的订阅 —— 推荐唯一入口
	//
	// 使用背景：
	// - 产品约定「每位注册用户应有 user_subscription 事实行」；历史上可能存在无行用户（老数据、仅注册未打开客户端等）。
	// - 本 RPC 在「已登录且仅能查自己」的前提下：若 DB 中尚无订阅行，则在本次请求内幂等写入当前应用下的默认免费档（FOREVER + type=free），再返回。
	//
	// 语义说明：
	// - 非「纯只读」：首次查询可能对当前用户产生 INSERT（与惰性迁移 / read-through 默认状态一致）。
	// - 幂等：重复调用不会重复创建（已有任意档位订阅时不会覆盖）。
	// - 须携带 X-App-Id（或与网关约定等价的 app 上下文），以便解析应用维度的免费套餐。
	//
	// 鉴权：仅允许查询 JWT 对应用户本人（CheckOwnership）。
	GetOrEnsureMySubscription(context.Context, *GetOrEnsureMySubscriptionRequest) (*GetOrEnsureMySubscriptionReply, error)
	// GetSubscriptionHistory 获取订阅历史记录
	GetSubscriptionHistory(context.Context, *GetSubscriptionHistoryRequest) (*GetSubscriptionHistoryReply, error)
	// GetSubscriptionOrder 获取订阅订单详情
	GetSubscriptionOrder(context.Context, *GetSubscriptionOrderRequest) (*GetSubscriptionOrderReply, error)
	// HandlePaymentSuccess 支付回调处理 (通常由 Payment Service 或 MQ 调用)
	HandlePaymentSuccess(context.Context, *HandlePaymentSuccessRequest) (*emptypb.Empty, error)
	// ListAppSubscriptions 获取应用的订阅用户列表（管理员视角）
	ListAppSubscriptions(context.Context, *ListAppSubscriptionsRequest) (*ListAppSubscriptionsReply, error)
	// ListPlanPricings 获取套餐的区域定价列表
	ListPlanPricings(context.Context, *ListPlanPricingsRequest) (*ListPlanPricingsReply, error)
	// ListPlans 获取所有订阅套餐
	ListPlans(context.Context, *ListPlansRequest) (*ListPlansReply, error)
	// ListSubscriptionOrders 获取订阅订单列表（管理员视角，按应用查询）
	ListSubscriptionOrders(context.Context, *ListSubscriptionOrdersRequest) (*ListSubscriptionOrdersReply, error)
	// PauseSubscription 暂停订阅
	PauseSubscription(context.Context, *PauseSubscriptionRequest) (*emptypb.Empty, error)
	// ProcessAutoRenewals 处理自动续费（用于定时任务）
	ProcessAutoRenewals(context.Context, *ProcessAutoRenewalsRequest) (*ProcessAutoRenewalsReply, error)
	// ResumeSubscription 恢复订阅
	ResumeSubscription(context.Context, *ResumeSubscriptionRequest) (*emptypb.Empty, error)
	// SetAutoRenew 设置自动续费
	SetAutoRenew(context.Context, *SetAutoRenewRequest) (*emptypb.Empty, error)
	// UpdateExpiredSubscriptions 批量更新过期订阅状态（用于定时任务）
	UpdateExpiredSubscriptions(context.Context, *UpdateExpiredSubscriptionsRequest) (*UpdateExpiredSubscriptionsReply, error)
	// UpdatePlan 更新订阅套餐
	UpdatePlan(context.Context, *UpdatePlanRequest) (*UpdatePlanReply, error)
	// UpdatePlanPricing 更新区域定价
	UpdatePlanPricing(context.Context, *UpdatePlanPricingRequest) (*UpdatePlanPricingReply, error)
}

func RegisterSubscriptionHTTPServer(s *http.Server, srv SubscriptionHTTPServer) {
	r := s.Route("/")
	r.GET("/subscription/v1/plans", _Subscription_ListPlans0_HTTP_Handler(srv))
	r.GET("/subscription/v1/my/{userId}", _Subscription_GetOrEnsureMySubscription0_HTTP_Handler(srv))
	r.POST("/subscription/v1/my/ensure-free", _Subscription_EnsureDefaultFreeSubscription0_HTTP_Handler(srv))
	r.POST("/subscription/v1/order", _Subscription_CreateSubscriptionOrder0_HTTP_Handler(srv))
	r.POST("/subscription/v1/payment/success", _Subscription_HandlePaymentSuccess0_HTTP_Handler(srv))
	r.POST("/subscription/v1/cancel", _Subscription_CancelSubscription0_HTTP_Handler(srv))
	r.POST("/subscription/v1/pause", _Subscription_PauseSubscription0_HTTP_Handler(srv))
	r.POST("/subscription/v1/resume", _Subscription_ResumeSubscription0_HTTP_Handler(srv))
	r.GET("/subscription/v1/history/{userId}", _Subscription_GetSubscriptionHistory0_HTTP_Handler(srv))
	r.POST("/subscription/v1/auto-renew", _Subscription_SetAutoRenew0_HTTP_Handler(srv))
	r.GET("/subscription/v1/expiring", _Subscription_GetExpiringSubscriptions0_HTTP_Handler(srv))
	r.POST("/subscription/v1/expired/update", _Subscription_UpdateExpiredSubscriptions0_HTTP_Handler(srv))
	r.POST("/subscription/v1/auto-renew/process", _Subscription_ProcessAutoRenewals0_HTTP_Handler(srv))
	r.POST("/subscription/v1/plans", _Subscription_CreatePlan0_HTTP_Handler(srv))
	r.PUT("/subscription/v1/plans/{planId}", _Subscription_UpdatePlan0_HTTP_Handler(srv))
	r.DELETE("/subscription/v1/plans/{planId}", _Subscription_DeletePlan0_HTTP_Handler(srv))
	r.GET("/subscription/v1/plans/{planId}/pricings", _Subscription_ListPlanPricings0_HTTP_Handler(srv))
	r.POST("/subscription/v1/plans/{planId}/pricings", _Subscription_CreatePlanPricing0_HTTP_Handler(srv))
	r.PUT("/subscription/v1/pricings/{planPricingId}", _Subscription_UpdatePlanPricing0_HTTP_Handler(srv))
	r.DELETE("/subscription/v1/pricings/{planPricingId}", _Subscription_DeletePlanPricing0_HTTP_Handler(srv))
	r.GET("/subscription/v1/orders", _Subscription_ListSubscriptionOrders0_HTTP_Handler(srv))
	r.GET("/subscription/v1/orders/{orderId}", _Subscription_GetSubscriptionOrder0_HTTP_Handler(srv))
	r.GET("/subscription/v1/app/subscriptions", _Subscription_ListAppSubscriptions0_HTTP_Handler(srv))
	r.GET("/subscription/v1/app/history", _Subscription_GetAppSubscriptionHistory0_HTTP_Handler(srv))
}

func _Subscription_ListPlans0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPlansRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionListPlans)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPlans(ctx, req.(*ListPlansRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPlansReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_GetOrEnsureMySubscription0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrEnsureMySubscriptionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionGetOrEnsureMySubscription)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrEnsureMySubscription(ctx, req.(*GetOrEnsureMySubscriptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrEnsureMySubscriptionReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_EnsureDefaultFreeSubscription0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnsureDefaultFreeSubscriptionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionEnsureDefaultFreeSubscription)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnsureDefaultFreeSubscription(ctx, req.(*EnsureDefaultFreeSubscriptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EnsureDefaultFreeSubscriptionReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_CreateSubscriptionOrder0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSubscriptionOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionCreateSubscriptionOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSubscriptionOrder(ctx, req.(*CreateSubscriptionOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSubscriptionOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_HandlePaymentSuccess0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HandlePaymentSuccessRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionHandlePaymentSuccess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HandlePaymentSuccess(ctx, req.(*HandlePaymentSuccessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Subscription_CancelSubscription0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelSubscriptionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionCancelSubscription)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelSubscription(ctx, req.(*CancelSubscriptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Subscription_PauseSubscription0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PauseSubscriptionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionPauseSubscription)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PauseSubscription(ctx, req.(*PauseSubscriptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Subscription_ResumeSubscription0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResumeSubscriptionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionResumeSubscription)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResumeSubscription(ctx, req.(*ResumeSubscriptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Subscription_GetSubscriptionHistory0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSubscriptionHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionGetSubscriptionHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSubscriptionHistory(ctx, req.(*GetSubscriptionHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSubscriptionHistoryReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_SetAutoRenew0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetAutoRenewRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionSetAutoRenew)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetAutoRenew(ctx, req.(*SetAutoRenewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Subscription_GetExpiringSubscriptions0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExpiringSubscriptionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionGetExpiringSubscriptions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExpiringSubscriptions(ctx, req.(*GetExpiringSubscriptionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetExpiringSubscriptionsReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_UpdateExpiredSubscriptions0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateExpiredSubscriptionsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionUpdateExpiredSubscriptions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateExpiredSubscriptions(ctx, req.(*UpdateExpiredSubscriptionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateExpiredSubscriptionsReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_ProcessAutoRenewals0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProcessAutoRenewalsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionProcessAutoRenewals)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ProcessAutoRenewals(ctx, req.(*ProcessAutoRenewalsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProcessAutoRenewalsReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_CreatePlan0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionCreatePlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePlan(ctx, req.(*CreatePlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePlanReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_UpdatePlan0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionUpdatePlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePlan(ctx, req.(*UpdatePlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePlanReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_DeletePlan0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePlanRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionDeletePlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePlan(ctx, req.(*DeletePlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeletePlanReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_ListPlanPricings0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPlanPricingsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionListPlanPricings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPlanPricings(ctx, req.(*ListPlanPricingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPlanPricingsReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_CreatePlanPricing0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePlanPricingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionCreatePlanPricing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePlanPricing(ctx, req.(*CreatePlanPricingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePlanPricingReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_UpdatePlanPricing0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePlanPricingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionUpdatePlanPricing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePlanPricing(ctx, req.(*UpdatePlanPricingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePlanPricingReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_DeletePlanPricing0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePlanPricingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionDeletePlanPricing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePlanPricing(ctx, req.(*DeletePlanPricingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeletePlanPricingReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_ListSubscriptionOrders0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSubscriptionOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionListSubscriptionOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSubscriptionOrders(ctx, req.(*ListSubscriptionOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSubscriptionOrdersReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_GetSubscriptionOrder0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSubscriptionOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionGetSubscriptionOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSubscriptionOrder(ctx, req.(*GetSubscriptionOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSubscriptionOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_ListAppSubscriptions0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAppSubscriptionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionListAppSubscriptions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAppSubscriptions(ctx, req.(*ListAppSubscriptionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAppSubscriptionsReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_GetAppSubscriptionHistory0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAppSubscriptionHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionGetAppSubscriptionHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAppSubscriptionHistory(ctx, req.(*GetAppSubscriptionHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAppSubscriptionHistoryReply)
		return ctx.Result(200, reply)
	}
}

type SubscriptionHTTPClient interface {
	// CancelSubscription 取消订阅
	CancelSubscription(ctx context.Context, req *CancelSubscriptionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// CreatePlan 创建订阅套餐
	CreatePlan(ctx context.Context, req *CreatePlanRequest, opts ...http.CallOption) (rsp *CreatePlanReply, err error)
	// CreatePlanPricing 创建区域定价
	CreatePlanPricing(ctx context.Context, req *CreatePlanPricingRequest, opts ...http.CallOption) (rsp *CreatePlanPricingReply, err error)
	// CreateSubscriptionOrder 创建订阅订单 (调用 Payment Service)
	CreateSubscriptionOrder(ctx context.Context, req *CreateSubscriptionOrderRequest, opts ...http.CallOption) (rsp *CreateSubscriptionOrderReply, err error)
	// DeletePlan 删除订阅套餐（软删除：仅标记删除时间，数据保留；ListPlans 不再返回）
	DeletePlan(ctx context.Context, req *DeletePlanRequest, opts ...http.CallOption) (rsp *DeletePlanReply, err error)
	// DeletePlanPricing 删除区域定价
	DeletePlanPricing(ctx context.Context, req *DeletePlanPricingRequest, opts ...http.CallOption) (rsp *DeletePlanPricingReply, err error)
	// EnsureDefaultFreeSubscription 显式幂等开通默认免费档（与 GetOrEnsureMySubscription 内 Ensure 逻辑一致）。
	// 一般客户端只需 GET GetOrEnsure；本接口可用于显式「同步」或调试。
	EnsureDefaultFreeSubscription(ctx context.Context, req *EnsureDefaultFreeSubscriptionRequest, opts ...http.CallOption) (rsp *EnsureDefaultFreeSubscriptionReply, err error)
	// GetAppSubscriptionHistory 获取应用的订阅历史记录（管理员视角）
	GetAppSubscriptionHistory(ctx context.Context, req *GetAppSubscriptionHistoryRequest, opts ...http.CallOption) (rsp *GetAppSubscriptionHistoryReply, err error)
	// GetExpiringSubscriptions 获取即将过期的订阅（用于定时任务）
	GetExpiringSubscriptions(ctx context.Context, req *GetExpiringSubscriptionsRequest, opts ...http.CallOption) (rsp *GetExpiringSubscriptionsReply, err error)
	// GetOrEnsureMySubscription 获取（并必要时初始化）当前用户的订阅 —— 推荐唯一入口
	//
	// 使用背景：
	// - 产品约定「每位注册用户应有 user_subscription 事实行」；历史上可能存在无行用户（老数据、仅注册未打开客户端等）。
	// - 本 RPC 在「已登录且仅能查自己」的前提下：若 DB 中尚无订阅行，则在本次请求内幂等写入当前应用下的默认免费档（FOREVER + type=free），再返回。
	//
	// 语义说明：
	// - 非「纯只读」：首次查询可能对当前用户产生 INSERT（与惰性迁移 / read-through 默认状态一致）。
	// - 幂等：重复调用不会重复创建（已有任意档位订阅时不会覆盖）。
	// - 须携带 X-App-Id（或与网关约定等价的 app 上下文），以便解析应用维度的免费套餐。
	//
	// 鉴权：仅允许查询 JWT 对应用户本人（CheckOwnership）。
	GetOrEnsureMySubscription(ctx context.Context, req *GetOrEnsureMySubscriptionRequest, opts ...http.CallOption) (rsp *GetOrEnsureMySubscriptionReply, err error)
	// GetSubscriptionHistory 获取订阅历史记录
	GetSubscriptionHistory(ctx context.Context, req *GetSubscriptionHistoryRequest, opts ...http.CallOption) (rsp *GetSubscriptionHistoryReply, err error)
	// GetSubscriptionOrder 获取订阅订单详情
	GetSubscriptionOrder(ctx context.Context, req *GetSubscriptionOrderRequest, opts ...http.CallOption) (rsp *GetSubscriptionOrderReply, err error)
	// HandlePaymentSuccess 支付回调处理 (通常由 Payment Service 或 MQ 调用)
	HandlePaymentSuccess(ctx context.Context, req *HandlePaymentSuccessRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ListAppSubscriptions 获取应用的订阅用户列表（管理员视角）
	ListAppSubscriptions(ctx context.Context, req *ListAppSubscriptionsRequest, opts ...http.CallOption) (rsp *ListAppSubscriptionsReply, err error)
	// ListPlanPricings 获取套餐的区域定价列表
	ListPlanPricings(ctx context.Context, req *ListPlanPricingsRequest, opts ...http.CallOption) (rsp *ListPlanPricingsReply, err error)
	// ListPlans 获取所有订阅套餐
	ListPlans(ctx context.Context, req *ListPlansRequest, opts ...http.CallOption) (rsp *ListPlansReply, err error)
	// ListSubscriptionOrders 获取订阅订单列表（管理员视角，按应用查询）
	ListSubscriptionOrders(ctx context.Context, req *ListSubscriptionOrdersRequest, opts ...http.CallOption) (rsp *ListSubscriptionOrdersReply, err error)
	// PauseSubscription 暂停订阅
	PauseSubscription(ctx context.Context, req *PauseSubscriptionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ProcessAutoRenewals 处理自动续费（用于定时任务）
	ProcessAutoRenewals(ctx context.Context, req *ProcessAutoRenewalsRequest, opts ...http.CallOption) (rsp *ProcessAutoRenewalsReply, err error)
	// ResumeSubscription 恢复订阅
	ResumeSubscription(ctx context.Context, req *ResumeSubscriptionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// SetAutoRenew 设置自动续费
	SetAutoRenew(ctx context.Context, req *SetAutoRenewRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UpdateExpiredSubscriptions 批量更新过期订阅状态（用于定时任务）
	UpdateExpiredSubscriptions(ctx context.Context, req *UpdateExpiredSubscriptionsRequest, opts ...http.CallOption) (rsp *UpdateExpiredSubscriptionsReply, err error)
	// UpdatePlan 更新订阅套餐
	UpdatePlan(ctx context.Context, req *UpdatePlanRequest, opts ...http.CallOption) (rsp *UpdatePlanReply, err error)
	// UpdatePlanPricing 更新区域定价
	UpdatePlanPricing(ctx context.Context, req *UpdatePlanPricingRequest, opts ...http.CallOption) (rsp *UpdatePlanPricingReply, err error)
}

type SubscriptionHTTPClientImpl struct {
	cc *http.Client
}

func NewSubscriptionHTTPClient(client *http.Client) SubscriptionHTTPClient {
	return &SubscriptionHTTPClientImpl{client}
}

// CancelSubscription 取消订阅
func (c *SubscriptionHTTPClientImpl) CancelSubscription(ctx context.Context, in *CancelSubscriptionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/subscription/v1/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionCancelSubscription))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreatePlan 创建订阅套餐
func (c *SubscriptionHTTPClientImpl) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...http.CallOption) (*CreatePlanReply, error) {
	var out CreatePlanReply
	pattern := "/subscription/v1/plans"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionCreatePlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreatePlanPricing 创建区域定价
func (c *SubscriptionHTTPClientImpl) CreatePlanPricing(ctx context.Context, in *CreatePlanPricingRequest, opts ...http.CallOption) (*CreatePlanPricingReply, error) {
	var out CreatePlanPricingReply
	pattern := "/subscription/v1/plans/{planId}/pricings"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionCreatePlanPricing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSubscriptionOrder 创建订阅订单 (调用 Payment Service)
func (c *SubscriptionHTTPClientImpl) CreateSubscriptionOrder(ctx context.Context, in *CreateSubscriptionOrderRequest, opts ...http.CallOption) (*CreateSubscriptionOrderReply, error) {
	var out CreateSubscriptionOrderReply
	pattern := "/subscription/v1/order"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionCreateSubscriptionOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeletePlan 删除订阅套餐（软删除：仅标记删除时间，数据保留；ListPlans 不再返回）
func (c *SubscriptionHTTPClientImpl) DeletePlan(ctx context.Context, in *DeletePlanRequest, opts ...http.CallOption) (*DeletePlanReply, error) {
	var out DeletePlanReply
	pattern := "/subscription/v1/plans/{planId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionDeletePlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeletePlanPricing 删除区域定价
func (c *SubscriptionHTTPClientImpl) DeletePlanPricing(ctx context.Context, in *DeletePlanPricingRequest, opts ...http.CallOption) (*DeletePlanPricingReply, error) {
	var out DeletePlanPricingReply
	pattern := "/subscription/v1/pricings/{planPricingId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionDeletePlanPricing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// EnsureDefaultFreeSubscription 显式幂等开通默认免费档（与 GetOrEnsureMySubscription 内 Ensure 逻辑一致）。
// 一般客户端只需 GET GetOrEnsure；本接口可用于显式「同步」或调试。
func (c *SubscriptionHTTPClientImpl) EnsureDefaultFreeSubscription(ctx context.Context, in *EnsureDefaultFreeSubscriptionRequest, opts ...http.CallOption) (*EnsureDefaultFreeSubscriptionReply, error) {
	var out EnsureDefaultFreeSubscriptionReply
	pattern := "/subscription/v1/my/ensure-free"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionEnsureDefaultFreeSubscription))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAppSubscriptionHistory 获取应用的订阅历史记录（管理员视角）
func (c *SubscriptionHTTPClientImpl) GetAppSubscriptionHistory(ctx context.Context, in *GetAppSubscriptionHistoryRequest, opts ...http.CallOption) (*GetAppSubscriptionHistoryReply, error) {
	var out GetAppSubscriptionHistoryReply
	pattern := "/subscription/v1/app/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionGetAppSubscriptionHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetExpiringSubscriptions 获取即将过期的订阅（用于定时任务）
func (c *SubscriptionHTTPClientImpl) GetExpiringSubscriptions(ctx context.Context, in *GetExpiringSubscriptionsRequest, opts ...http.CallOption) (*GetExpiringSubscriptionsReply, error) {
	var out GetExpiringSubscriptionsReply
	pattern := "/subscription/v1/expiring"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionGetExpiringSubscriptions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetOrEnsureMySubscription 获取（并必要时初始化）当前用户的订阅 —— 推荐唯一入口
//
// 使用背景：
// - 产品约定「每位注册用户应有 user_subscription 事实行」；历史上可能存在无行用户（老数据、仅注册未打开客户端等）。
// - 本 RPC 在「已登录且仅能查自己」的前提下：若 DB 中尚无订阅行，则在本次请求内幂等写入当前应用下的默认免费档（FOREVER + type=free），再返回。
//
// 语义说明：
// - 非「纯只读」：首次查询可能对当前用户产生 INSERT（与惰性迁移 / read-through 默认状态一致）。
// - 幂等：重复调用不会重复创建（已有任意档位订阅时不会覆盖）。
// - 须携带 X-App-Id（或与网关约定等价的 app 上下文），以便解析应用维度的免费套餐。
//
// 鉴权：仅允许查询 JWT 对应用户本人（CheckOwnership）。
func (c *SubscriptionHTTPClientImpl) GetOrEnsureMySubscription(ctx context.Context, in *GetOrEnsureMySubscriptionRequest, opts ...http.CallOption) (*GetOrEnsureMySubscriptionReply, error) {
	var out GetOrEnsureMySubscriptionReply
	pattern := "/subscription/v1/my/{userId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionGetOrEnsureMySubscription))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSubscriptionHistory 获取订阅历史记录
func (c *SubscriptionHTTPClientImpl) GetSubscriptionHistory(ctx context.Context, in *GetSubscriptionHistoryRequest, opts ...http.CallOption) (*GetSubscriptionHistoryReply, error) {
	var out GetSubscriptionHistoryReply
	pattern := "/subscription/v1/history/{userId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionGetSubscriptionHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSubscriptionOrder 获取订阅订单详情
func (c *SubscriptionHTTPClientImpl) GetSubscriptionOrder(ctx context.Context, in *GetSubscriptionOrderRequest, opts ...http.CallOption) (*GetSubscriptionOrderReply, error) {
	var out GetSubscriptionOrderReply
	pattern := "/subscription/v1/orders/{orderId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionGetSubscriptionOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HandlePaymentSuccess 支付回调处理 (通常由 Payment Service 或 MQ 调用)
func (c *SubscriptionHTTPClientImpl) HandlePaymentSuccess(ctx context.Context, in *HandlePaymentSuccessRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/subscription/v1/payment/success"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionHandlePaymentSuccess))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAppSubscriptions 获取应用的订阅用户列表（管理员视角）
func (c *SubscriptionHTTPClientImpl) ListAppSubscriptions(ctx context.Context, in *ListAppSubscriptionsRequest, opts ...http.CallOption) (*ListAppSubscriptionsReply, error) {
	var out ListAppSubscriptionsReply
	pattern := "/subscription/v1/app/subscriptions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionListAppSubscriptions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPlanPricings 获取套餐的区域定价列表
func (c *SubscriptionHTTPClientImpl) ListPlanPricings(ctx context.Context, in *ListPlanPricingsRequest, opts ...http.CallOption) (*ListPlanPricingsReply, error) {
	var out ListPlanPricingsReply
	pattern := "/subscription/v1/plans/{planId}/pricings"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionListPlanPricings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPlans 获取所有订阅套餐
func (c *SubscriptionHTTPClientImpl) ListPlans(ctx context.Context, in *ListPlansRequest, opts ...http.CallOption) (*ListPlansReply, error) {
	var out ListPlansReply
	pattern := "/subscription/v1/plans"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionListPlans))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSubscriptionOrders 获取订阅订单列表（管理员视角，按应用查询）
func (c *SubscriptionHTTPClientImpl) ListSubscriptionOrders(ctx context.Context, in *ListSubscriptionOrdersRequest, opts ...http.CallOption) (*ListSubscriptionOrdersReply, error) {
	var out ListSubscriptionOrdersReply
	pattern := "/subscription/v1/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionListSubscriptionOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PauseSubscription 暂停订阅
func (c *SubscriptionHTTPClientImpl) PauseSubscription(ctx context.Context, in *PauseSubscriptionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/subscription/v1/pause"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionPauseSubscription))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ProcessAutoRenewals 处理自动续费（用于定时任务）
func (c *SubscriptionHTTPClientImpl) ProcessAutoRenewals(ctx context.Context, in *ProcessAutoRenewalsRequest, opts ...http.CallOption) (*ProcessAutoRenewalsReply, error) {
	var out ProcessAutoRenewalsReply
	pattern := "/subscription/v1/auto-renew/process"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionProcessAutoRenewals))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResumeSubscription 恢复订阅
func (c *SubscriptionHTTPClientImpl) ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/subscription/v1/resume"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionResumeSubscription))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetAutoRenew 设置自动续费
func (c *SubscriptionHTTPClientImpl) SetAutoRenew(ctx context.Context, in *SetAutoRenewRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/subscription/v1/auto-renew"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionSetAutoRenew))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateExpiredSubscriptions 批量更新过期订阅状态（用于定时任务）
func (c *SubscriptionHTTPClientImpl) UpdateExpiredSubscriptions(ctx context.Context, in *UpdateExpiredSubscriptionsRequest, opts ...http.CallOption) (*UpdateExpiredSubscriptionsReply, error) {
	var out UpdateExpiredSubscriptionsReply
	pattern := "/subscription/v1/expired/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionUpdateExpiredSubscriptions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePlan 更新订阅套餐
func (c *SubscriptionHTTPClientImpl) UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...http.CallOption) (*UpdatePlanReply, error) {
	var out UpdatePlanReply
	pattern := "/subscription/v1/plans/{planId}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionUpdatePlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePlanPricing 更新区域定价
func (c *SubscriptionHTTPClientImpl) UpdatePlanPricing(ctx context.Context, in *UpdatePlanPricingRequest, opts ...http.CallOption) (*UpdatePlanPricingReply, error) {
	var out UpdatePlanPricingReply
	pattern := "/subscription/v1/pricings/{planPricingId}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionUpdatePlanPricing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
