// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v5.29.3
// source: api/subscription/v1/subscription.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSubscriptionCreateSubscriptionOrder = "/subscription.v1.Subscription/CreateSubscriptionOrder"
const OperationSubscriptionGetMySubscription = "/subscription.v1.Subscription/GetMySubscription"
const OperationSubscriptionHandlePaymentSuccess = "/subscription.v1.Subscription/HandlePaymentSuccess"
const OperationSubscriptionListPlans = "/subscription.v1.Subscription/ListPlans"

type SubscriptionHTTPServer interface {
	// CreateSubscriptionOrder 创建订阅订单 (调用 Payment Service)
	CreateSubscriptionOrder(context.Context, *CreateSubscriptionOrderRequest) (*CreateSubscriptionOrderReply, error)
	// GetMySubscription 获取用户的订阅状态
	GetMySubscription(context.Context, *GetMySubscriptionRequest) (*GetMySubscriptionReply, error)
	// HandlePaymentSuccess 支付回调处理 (通常由 Payment Service 或 MQ 调用)
	HandlePaymentSuccess(context.Context, *HandlePaymentSuccessRequest) (*HandlePaymentSuccessReply, error)
	// ListPlans 获取所有订阅套餐
	ListPlans(context.Context, *ListPlansRequest) (*ListPlansReply, error)
}

func RegisterSubscriptionHTTPServer(s *http.Server, srv SubscriptionHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/subscription/plans", _Subscription_ListPlans0_HTTP_Handler(srv))
	r.GET("/v1/subscription/my/{uid}", _Subscription_GetMySubscription0_HTTP_Handler(srv))
	r.POST("/v1/subscription/order", _Subscription_CreateSubscriptionOrder0_HTTP_Handler(srv))
	r.POST("/v1/subscription/payment/success", _Subscription_HandlePaymentSuccess0_HTTP_Handler(srv))
}

func _Subscription_ListPlans0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPlansRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionListPlans)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPlans(ctx, req.(*ListPlansRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPlansReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_GetMySubscription0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMySubscriptionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionGetMySubscription)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMySubscription(ctx, req.(*GetMySubscriptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMySubscriptionReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_CreateSubscriptionOrder0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSubscriptionOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionCreateSubscriptionOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSubscriptionOrder(ctx, req.(*CreateSubscriptionOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSubscriptionOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Subscription_HandlePaymentSuccess0_HTTP_Handler(srv SubscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HandlePaymentSuccessRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscriptionHandlePaymentSuccess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HandlePaymentSuccess(ctx, req.(*HandlePaymentSuccessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HandlePaymentSuccessReply)
		return ctx.Result(200, reply)
	}
}

type SubscriptionHTTPClient interface {
	// CreateSubscriptionOrder 创建订阅订单 (调用 Payment Service)
	CreateSubscriptionOrder(ctx context.Context, req *CreateSubscriptionOrderRequest, opts ...http.CallOption) (rsp *CreateSubscriptionOrderReply, err error)
	// GetMySubscription 获取用户的订阅状态
	GetMySubscription(ctx context.Context, req *GetMySubscriptionRequest, opts ...http.CallOption) (rsp *GetMySubscriptionReply, err error)
	// HandlePaymentSuccess 支付回调处理 (通常由 Payment Service 或 MQ 调用)
	HandlePaymentSuccess(ctx context.Context, req *HandlePaymentSuccessRequest, opts ...http.CallOption) (rsp *HandlePaymentSuccessReply, err error)
	// ListPlans 获取所有订阅套餐
	ListPlans(ctx context.Context, req *ListPlansRequest, opts ...http.CallOption) (rsp *ListPlansReply, err error)
}

type SubscriptionHTTPClientImpl struct {
	cc *http.Client
}

func NewSubscriptionHTTPClient(client *http.Client) SubscriptionHTTPClient {
	return &SubscriptionHTTPClientImpl{client}
}

// CreateSubscriptionOrder 创建订阅订单 (调用 Payment Service)
func (c *SubscriptionHTTPClientImpl) CreateSubscriptionOrder(ctx context.Context, in *CreateSubscriptionOrderRequest, opts ...http.CallOption) (*CreateSubscriptionOrderReply, error) {
	var out CreateSubscriptionOrderReply
	pattern := "/v1/subscription/order"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionCreateSubscriptionOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMySubscription 获取用户的订阅状态
func (c *SubscriptionHTTPClientImpl) GetMySubscription(ctx context.Context, in *GetMySubscriptionRequest, opts ...http.CallOption) (*GetMySubscriptionReply, error) {
	var out GetMySubscriptionReply
	pattern := "/v1/subscription/my/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionGetMySubscription))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HandlePaymentSuccess 支付回调处理 (通常由 Payment Service 或 MQ 调用)
func (c *SubscriptionHTTPClientImpl) HandlePaymentSuccess(ctx context.Context, in *HandlePaymentSuccessRequest, opts ...http.CallOption) (*HandlePaymentSuccessReply, error) {
	var out HandlePaymentSuccessReply
	pattern := "/v1/subscription/payment/success"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscriptionHandlePaymentSuccess))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPlans 获取所有订阅套餐
func (c *SubscriptionHTTPClientImpl) ListPlans(ctx context.Context, in *ListPlansRequest, opts ...http.CallOption) (*ListPlansReply, error) {
	var out ListPlansReply
	pattern := "/v1/subscription/plans"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscriptionListPlans))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
