// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/subscription/v1/subscription.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Subscription_ListPlans_FullMethodName               = "/subscription.v1.Subscription/ListPlans"
	Subscription_GetMySubscription_FullMethodName       = "/subscription.v1.Subscription/GetMySubscription"
	Subscription_CreateSubscriptionOrder_FullMethodName = "/subscription.v1.Subscription/CreateSubscriptionOrder"
	Subscription_HandlePaymentSuccess_FullMethodName    = "/subscription.v1.Subscription/HandlePaymentSuccess"
)

// SubscriptionClient is the client API for Subscription service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionClient interface {
	// 获取所有订阅套餐
	ListPlans(ctx context.Context, in *ListPlansRequest, opts ...grpc.CallOption) (*ListPlansReply, error)
	// 获取用户的订阅状态
	GetMySubscription(ctx context.Context, in *GetMySubscriptionRequest, opts ...grpc.CallOption) (*GetMySubscriptionReply, error)
	// 创建订阅订单 (调用 Payment Service)
	CreateSubscriptionOrder(ctx context.Context, in *CreateSubscriptionOrderRequest, opts ...grpc.CallOption) (*CreateSubscriptionOrderReply, error)
	// 支付回调处理 (通常由 Payment Service 或 MQ 调用)
	HandlePaymentSuccess(ctx context.Context, in *HandlePaymentSuccessRequest, opts ...grpc.CallOption) (*HandlePaymentSuccessReply, error)
}

type subscriptionClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionClient(cc grpc.ClientConnInterface) SubscriptionClient {
	return &subscriptionClient{cc}
}

func (c *subscriptionClient) ListPlans(ctx context.Context, in *ListPlansRequest, opts ...grpc.CallOption) (*ListPlansReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlansReply)
	err := c.cc.Invoke(ctx, Subscription_ListPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) GetMySubscription(ctx context.Context, in *GetMySubscriptionRequest, opts ...grpc.CallOption) (*GetMySubscriptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMySubscriptionReply)
	err := c.cc.Invoke(ctx, Subscription_GetMySubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) CreateSubscriptionOrder(ctx context.Context, in *CreateSubscriptionOrderRequest, opts ...grpc.CallOption) (*CreateSubscriptionOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubscriptionOrderReply)
	err := c.cc.Invoke(ctx, Subscription_CreateSubscriptionOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) HandlePaymentSuccess(ctx context.Context, in *HandlePaymentSuccessRequest, opts ...grpc.CallOption) (*HandlePaymentSuccessReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlePaymentSuccessReply)
	err := c.cc.Invoke(ctx, Subscription_HandlePaymentSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionServer is the server API for Subscription service.
// All implementations must embed UnimplementedSubscriptionServer
// for forward compatibility.
type SubscriptionServer interface {
	// 获取所有订阅套餐
	ListPlans(context.Context, *ListPlansRequest) (*ListPlansReply, error)
	// 获取用户的订阅状态
	GetMySubscription(context.Context, *GetMySubscriptionRequest) (*GetMySubscriptionReply, error)
	// 创建订阅订单 (调用 Payment Service)
	CreateSubscriptionOrder(context.Context, *CreateSubscriptionOrderRequest) (*CreateSubscriptionOrderReply, error)
	// 支付回调处理 (通常由 Payment Service 或 MQ 调用)
	HandlePaymentSuccess(context.Context, *HandlePaymentSuccessRequest) (*HandlePaymentSuccessReply, error)
	mustEmbedUnimplementedSubscriptionServer()
}

// UnimplementedSubscriptionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionServer struct{}

func (UnimplementedSubscriptionServer) ListPlans(context.Context, *ListPlansRequest) (*ListPlansReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlans not implemented")
}
func (UnimplementedSubscriptionServer) GetMySubscription(context.Context, *GetMySubscriptionRequest) (*GetMySubscriptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMySubscription not implemented")
}
func (UnimplementedSubscriptionServer) CreateSubscriptionOrder(context.Context, *CreateSubscriptionOrderRequest) (*CreateSubscriptionOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscriptionOrder not implemented")
}
func (UnimplementedSubscriptionServer) HandlePaymentSuccess(context.Context, *HandlePaymentSuccessRequest) (*HandlePaymentSuccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePaymentSuccess not implemented")
}
func (UnimplementedSubscriptionServer) mustEmbedUnimplementedSubscriptionServer() {}
func (UnimplementedSubscriptionServer) testEmbeddedByValue()                      {}

// UnsafeSubscriptionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServer will
// result in compilation errors.
type UnsafeSubscriptionServer interface {
	mustEmbedUnimplementedSubscriptionServer()
}

func RegisterSubscriptionServer(s grpc.ServiceRegistrar, srv SubscriptionServer) {
	// If the following call pancis, it indicates UnimplementedSubscriptionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Subscription_ServiceDesc, srv)
}

func _Subscription_ListPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).ListPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_ListPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).ListPlans(ctx, req.(*ListPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_GetMySubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMySubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).GetMySubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_GetMySubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).GetMySubscription(ctx, req.(*GetMySubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_CreateSubscriptionOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).CreateSubscriptionOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_CreateSubscriptionOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).CreateSubscriptionOrder(ctx, req.(*CreateSubscriptionOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_HandlePaymentSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandlePaymentSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).HandlePaymentSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_HandlePaymentSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).HandlePaymentSuccess(ctx, req.(*HandlePaymentSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Subscription_ServiceDesc is the grpc.ServiceDesc for Subscription service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subscription_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscription.v1.Subscription",
	HandlerType: (*SubscriptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPlans",
			Handler:    _Subscription_ListPlans_Handler,
		},
		{
			MethodName: "GetMySubscription",
			Handler:    _Subscription_GetMySubscription_Handler,
		},
		{
			MethodName: "CreateSubscriptionOrder",
			Handler:    _Subscription_CreateSubscriptionOrder_Handler,
		},
		{
			MethodName: "HandlePaymentSuccess",
			Handler:    _Subscription_HandlePaymentSuccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/subscription/v1/subscription.proto",
}
