// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: subscription.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	DurationDays  int32                  `protobuf:"varint,6,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"` // 持续天数
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`                                      // free, pro, enterprise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Plan) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Plan) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *Plan) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

type ListPlansReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*Plan                `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansReply) Reset() {
	*x = ListPlansReply{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansReply) ProtoMessage() {}

func (x *ListPlansReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansReply.ProtoReflect.Descriptor instead.
func (*ListPlansReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *ListPlansReply) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type GetMySubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySubscriptionRequest) Reset() {
	*x = GetMySubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySubscriptionRequest) ProtoMessage() {}

func (x *GetMySubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetMySubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetMySubscriptionRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetMySubscriptionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                         // active, expired, paused, cancelled
	AutoRenew     bool                   `protobuf:"varint,6,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"` // 是否自动续费
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySubscriptionReply) Reset() {
	*x = GetMySubscriptionReply{}
	mi := &file_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySubscriptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySubscriptionReply) ProtoMessage() {}

func (x *GetMySubscriptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySubscriptionReply.ProtoReflect.Descriptor instead.
func (*GetMySubscriptionReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *GetMySubscriptionReply) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetMySubscriptionReply) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *GetMySubscriptionReply) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetMySubscriptionReply) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetMySubscriptionReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMySubscriptionReply) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

type CreateSubscriptionOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // alipay, wechatpay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionOrderRequest) Reset() {
	*x = CreateSubscriptionOrderRequest{}
	mi := &file_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionOrderRequest) ProtoMessage() {}

func (x *CreateSubscriptionOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionOrderRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSubscriptionOrderRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateSubscriptionOrderRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateSubscriptionOrderRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CreateSubscriptionOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`       // 业务订单号
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // 支付流水号
	PayUrl        string                 `protobuf:"bytes,3,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	PayCode       string                 `protobuf:"bytes,4,opt,name=pay_code,json=payCode,proto3" json:"pay_code,omitempty"`
	PayParams     string                 `protobuf:"bytes,5,opt,name=pay_params,json=payParams,proto3" json:"pay_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionOrderReply) Reset() {
	*x = CreateSubscriptionOrderReply{}
	mi := &file_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionOrderReply) ProtoMessage() {}

func (x *CreateSubscriptionOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionOrderReply.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionOrderReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSubscriptionOrderReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPayCode() string {
	if x != nil {
		return x.PayCode
	}
	return ""
}

func (x *CreateSubscriptionOrderReply) GetPayParams() string {
	if x != nil {
		return x.PayParams
	}
	return ""
}

type HandlePaymentSuccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePaymentSuccessRequest) Reset() {
	*x = HandlePaymentSuccessRequest{}
	mi := &file_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePaymentSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePaymentSuccessRequest) ProtoMessage() {}

func (x *HandlePaymentSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePaymentSuccessRequest.ProtoReflect.Descriptor instead.
func (*HandlePaymentSuccessRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *HandlePaymentSuccessRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *HandlePaymentSuccessRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *HandlePaymentSuccessRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type HandlePaymentSuccessReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePaymentSuccessReply) Reset() {
	*x = HandlePaymentSuccessReply{}
	mi := &file_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePaymentSuccessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePaymentSuccessReply) ProtoMessage() {}

func (x *HandlePaymentSuccessReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePaymentSuccessReply.ProtoReflect.Descriptor instead.
func (*HandlePaymentSuccessReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *HandlePaymentSuccessReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 取消订阅
type CancelSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 取消原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *CancelSubscriptionRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CancelSubscriptionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelSubscriptionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionReply) Reset() {
	*x = CancelSubscriptionReply{}
	mi := &file_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionReply) ProtoMessage() {}

func (x *CancelSubscriptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionReply.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *CancelSubscriptionReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelSubscriptionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 暂停订阅
type PauseSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 暂停原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSubscriptionRequest) Reset() {
	*x = PauseSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSubscriptionRequest) ProtoMessage() {}

func (x *PauseSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*PauseSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *PauseSubscriptionRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PauseSubscriptionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PauseSubscriptionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSubscriptionReply) Reset() {
	*x = PauseSubscriptionReply{}
	mi := &file_subscription_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSubscriptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSubscriptionReply) ProtoMessage() {}

func (x *PauseSubscriptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSubscriptionReply.ProtoReflect.Descriptor instead.
func (*PauseSubscriptionReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{12}
}

func (x *PauseSubscriptionReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseSubscriptionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 恢复订阅
type ResumeSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSubscriptionRequest) Reset() {
	*x = ResumeSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSubscriptionRequest) ProtoMessage() {}

func (x *ResumeSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ResumeSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{13}
}

func (x *ResumeSubscriptionRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ResumeSubscriptionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSubscriptionReply) Reset() {
	*x = ResumeSubscriptionReply{}
	mi := &file_subscription_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSubscriptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSubscriptionReply) ProtoMessage() {}

func (x *ResumeSubscriptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSubscriptionReply.ProtoReflect.Descriptor instead.
func (*ResumeSubscriptionReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{14}
}

func (x *ResumeSubscriptionReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeSubscriptionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 订阅历史记录
type SubscriptionHistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PlanName      string                 `protobuf:"bytes,3,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // active, expired, paused, cancelled
	Action        string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"` // created, renewed, upgraded, paused, resumed, cancelled
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionHistoryItem) Reset() {
	*x = SubscriptionHistoryItem{}
	mi := &file_subscription_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionHistoryItem) ProtoMessage() {}

func (x *SubscriptionHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionHistoryItem.ProtoReflect.Descriptor instead.
func (*SubscriptionHistoryItem) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{15}
}

func (x *SubscriptionHistoryItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubscriptionHistoryItem) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SubscriptionHistoryItem) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *SubscriptionHistoryItem) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SubscriptionHistoryItem) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SubscriptionHistoryItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubscriptionHistoryItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SubscriptionHistoryItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetSubscriptionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，从1开始
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量，默认10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionHistoryRequest) Reset() {
	*x = GetSubscriptionHistoryRequest{}
	mi := &file_subscription_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionHistoryRequest) ProtoMessage() {}

func (x *GetSubscriptionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{16}
}

func (x *GetSubscriptionHistoryRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetSubscriptionHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSubscriptionHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetSubscriptionHistoryReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*SubscriptionHistoryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                      `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                      `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionHistoryReply) Reset() {
	*x = GetSubscriptionHistoryReply{}
	mi := &file_subscription_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionHistoryReply) ProtoMessage() {}

func (x *GetSubscriptionHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionHistoryReply.ProtoReflect.Descriptor instead.
func (*GetSubscriptionHistoryReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{17}
}

func (x *GetSubscriptionHistoryReply) GetItems() []*SubscriptionHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetSubscriptionHistoryReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetSubscriptionHistoryReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSubscriptionHistoryReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 自动续费设置
type SetAutoRenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AutoRenew     bool                   `protobuf:"varint,2,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"` // true: 开启自动续费, false: 关闭自动续费
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoRenewRequest) Reset() {
	*x = SetAutoRenewRequest{}
	mi := &file_subscription_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoRenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoRenewRequest) ProtoMessage() {}

func (x *SetAutoRenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoRenewRequest.ProtoReflect.Descriptor instead.
func (*SetAutoRenewRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{18}
}

func (x *SetAutoRenewRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SetAutoRenewRequest) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

type SetAutoRenewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoRenewReply) Reset() {
	*x = SetAutoRenewReply{}
	mi := &file_subscription_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoRenewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoRenewReply) ProtoMessage() {}

func (x *SetAutoRenewReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoRenewReply.ProtoReflect.Descriptor instead.
func (*SetAutoRenewReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{19}
}

func (x *SetAutoRenewReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetAutoRenewReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取即将过期的订阅
type GetExpiringSubscriptionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DaysBeforeExpiry int32                  `protobuf:"varint,1,opt,name=days_before_expiry,json=daysBeforeExpiry,proto3" json:"days_before_expiry,omitempty"` // 过期前多少天，默认7天
	Page             int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                                                   // 页码，从1开始
	PageSize         int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                           // 每页数量，默认10
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetExpiringSubscriptionsRequest) Reset() {
	*x = GetExpiringSubscriptionsRequest{}
	mi := &file_subscription_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpiringSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpiringSubscriptionsRequest) ProtoMessage() {}

func (x *GetExpiringSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpiringSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetExpiringSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{20}
}

func (x *GetExpiringSubscriptionsRequest) GetDaysBeforeExpiry() int32 {
	if x != nil {
		return x.DaysBeforeExpiry
	}
	return 0
}

func (x *GetExpiringSubscriptionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExpiringSubscriptionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SubscriptionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PlanName      string                 `protobuf:"bytes,3,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	AutoRenew     bool                   `protobuf:"varint,6,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionInfo) Reset() {
	*x = SubscriptionInfo{}
	mi := &file_subscription_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionInfo) ProtoMessage() {}

func (x *SubscriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionInfo.ProtoReflect.Descriptor instead.
func (*SubscriptionInfo) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{21}
}

func (x *SubscriptionInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SubscriptionInfo) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SubscriptionInfo) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *SubscriptionInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SubscriptionInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SubscriptionInfo) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

func (x *SubscriptionInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetExpiringSubscriptionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*SubscriptionInfo    `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpiringSubscriptionsReply) Reset() {
	*x = GetExpiringSubscriptionsReply{}
	mi := &file_subscription_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpiringSubscriptionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpiringSubscriptionsReply) ProtoMessage() {}

func (x *GetExpiringSubscriptionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpiringSubscriptionsReply.ProtoReflect.Descriptor instead.
func (*GetExpiringSubscriptionsReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{22}
}

func (x *GetExpiringSubscriptionsReply) GetSubscriptions() []*SubscriptionInfo {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *GetExpiringSubscriptionsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetExpiringSubscriptionsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExpiringSubscriptionsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 批量更新过期订阅
type UpdateExpiredSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpiredSubscriptionsRequest) Reset() {
	*x = UpdateExpiredSubscriptionsRequest{}
	mi := &file_subscription_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpiredSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpiredSubscriptionsRequest) ProtoMessage() {}

func (x *UpdateExpiredSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpiredSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpiredSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{23}
}

type UpdateExpiredSubscriptionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	UpdatedUids   []uint64               `protobuf:"varint,2,rep,packed,name=updated_uids,json=updatedUids,proto3" json:"updated_uids,omitempty"` // 更新的用户ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpiredSubscriptionsReply) Reset() {
	*x = UpdateExpiredSubscriptionsReply{}
	mi := &file_subscription_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpiredSubscriptionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpiredSubscriptionsReply) ProtoMessage() {}

func (x *UpdateExpiredSubscriptionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpiredSubscriptionsReply.ProtoReflect.Descriptor instead.
func (*UpdateExpiredSubscriptionsReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateExpiredSubscriptionsReply) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *UpdateExpiredSubscriptionsReply) GetUpdatedUids() []uint64 {
	if x != nil {
		return x.UpdatedUids
	}
	return nil
}

// 自动续费处理
type ProcessAutoRenewalsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DaysBeforeExpiry int32                  `protobuf:"varint,1,opt,name=days_before_expiry,json=daysBeforeExpiry,proto3" json:"days_before_expiry,omitempty"` // 提前多少天续费，默认3天
	DryRun           bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`                                 // 是否为测试运行
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessAutoRenewalsRequest) Reset() {
	*x = ProcessAutoRenewalsRequest{}
	mi := &file_subscription_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAutoRenewalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAutoRenewalsRequest) ProtoMessage() {}

func (x *ProcessAutoRenewalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAutoRenewalsRequest.ProtoReflect.Descriptor instead.
func (*ProcessAutoRenewalsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{25}
}

func (x *ProcessAutoRenewalsRequest) GetDaysBeforeExpiry() int32 {
	if x != nil {
		return x.DaysBeforeExpiry
	}
	return 0
}

func (x *ProcessAutoRenewalsRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type AutoRenewResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	OrderId       string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,5,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoRenewResult) Reset() {
	*x = AutoRenewResult{}
	mi := &file_subscription_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoRenewResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoRenewResult) ProtoMessage() {}

func (x *AutoRenewResult) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoRenewResult.ProtoReflect.Descriptor instead.
func (*AutoRenewResult) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{26}
}

func (x *AutoRenewResult) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AutoRenewResult) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *AutoRenewResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AutoRenewResult) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AutoRenewResult) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *AutoRenewResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ProcessAutoRenewalsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`       // 总共需要处理的数量
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功的数量
	FailedCount   int32                  `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`    // 失败的数量
	Results       []*AutoRenewResult     `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessAutoRenewalsReply) Reset() {
	*x = ProcessAutoRenewalsReply{}
	mi := &file_subscription_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAutoRenewalsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAutoRenewalsReply) ProtoMessage() {}

func (x *ProcessAutoRenewalsReply) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAutoRenewalsReply.ProtoReflect.Descriptor instead.
func (*ProcessAutoRenewalsReply) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{27}
}

func (x *ProcessAutoRenewalsReply) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ProcessAutoRenewalsReply) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ProcessAutoRenewalsReply) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *ProcessAutoRenewalsReply) GetResults() []*AutoRenewResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\x0fsubscription.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xb7\x01\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12#\n" +
	"\rduration_days\x18\x06 \x01(\x05R\fdurationDays\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\"\x12\n" +
	"\x10ListPlansRequest\"=\n" +
	"\x0eListPlansReply\x12+\n" +
	"\x05plans\x18\x01 \x03(\v2\x15.subscription.v1.PlanR\x05plans\"5\n" +
	"\x18GetMySubscriptionRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\"\xbf\x01\n" +
	"\x16GetMySubscriptionReply\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\x06 \x01(\bR\tautoRenew\"\xa0\x01\n" +
	"\x1eCreateSubscriptionOrderRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\x12\"\n" +
	"\aplan_id\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x06planId\x12?\n" +
	"\x0epayment_method\x18\x03 \x01(\tB\x18\xfaB\x15r\x13R\x06alipayR\twechatpayR\rpaymentMethod\"\xab\x01\n" +
	"\x1cCreateSubscriptionOrderReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x17\n" +
	"\apay_url\x18\x03 \x01(\tR\x06payUrl\x12\x19\n" +
	"\bpay_code\x18\x04 \x01(\tR\apayCode\x12\x1d\n" +
	"\n" +
	"pay_params\x18\x05 \x01(\tR\tpayParams\"\x95\x01\n" +
	"\x1bHandlePaymentSuccessRequest\x12$\n" +
	"\border_id\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\aorderId\x12(\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\tpaymentId\x12&\n" +
	"\x06amount\x18\x03 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x06amount\"5\n" +
	"\x19HandlePaymentSuccessReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\x19CancelSubscriptionRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"M\n" +
	"\x17CancelSubscriptionReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x18PauseSubscriptionRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"L\n" +
	"\x16PauseSubscriptionReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x19ResumeSubscriptionRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\"M\n" +
	"\x17ResumeSubscriptionReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe8\x01\n" +
	"\x17SubscriptionHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1b\n" +
	"\tplan_name\x18\x03 \x01(\tR\bplanName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"k\n" +
	"\x1dGetSubscriptionHistoryRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa4\x01\n" +
	"\x1bGetSubscriptionHistoryReply\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.subscription.v1.SubscriptionHistoryItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"O\n" +
	"\x13SetAutoRenewRequest\x12\x19\n" +
	"\x03uid\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x03uid\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\x02 \x01(\bR\tautoRenew\"G\n" +
	"\x11SetAutoRenewReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8b\x01\n" +
	"\x1fGetExpiringSubscriptionsRequest\x127\n" +
	"\x12days_before_expiry\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x1e(\x01R\x10daysBeforeExpiry\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xcb\x01\n" +
	"\x10SubscriptionInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1b\n" +
	"\tplan_name\x18\x03 \x01(\tR\bplanName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\x06 \x01(\bR\tautoRenew\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\"\xaf\x01\n" +
	"\x1dGetExpiringSubscriptionsReply\x12G\n" +
	"\rsubscriptions\x18\x01 \x03(\v2!.subscription.v1.SubscriptionInfoR\rsubscriptions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"#\n" +
	"!UpdateExpiredSubscriptionsRequest\"i\n" +
	"\x1fUpdateExpiredSubscriptionsReply\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\x12!\n" +
	"\fupdated_uids\x18\x02 \x03(\x04R\vupdatedUids\"n\n" +
	"\x1aProcessAutoRenewalsRequest\x127\n" +
	"\x12days_before_expiry\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x1e(\x01R\x10daysBeforeExpiry\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"\xb5\x01\n" +
	"\x0fAutoRenewResult\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x05 \x01(\tR\tpaymentId\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xbf\x01\n" +
	"\x18ProcessAutoRenewalsReply\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x05R\vfailedCount\x12:\n" +
	"\aresults\x18\x04 \x03(\v2 .subscription.v1.AutoRenewResultR\aresults2\x91\x0e\n" +
	"\fSubscription\x12o\n" +
	"\tListPlans\x12!.subscription.v1.ListPlansRequest\x1a\x1f.subscription.v1.ListPlansReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/subscription/plans\x12\x8a\x01\n" +
	"\x11GetMySubscription\x12).subscription.v1.GetMySubscriptionRequest\x1a'.subscription.v1.GetMySubscriptionReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/subscription/my/{uid}\x12\x9c\x01\n" +
	"\x17CreateSubscriptionOrder\x12/.subscription.v1.CreateSubscriptionOrderRequest\x1a-.subscription.v1.CreateSubscriptionOrderReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/subscription/order\x12\x9d\x01\n" +
	"\x14HandlePaymentSuccess\x12,.subscription.v1.HandlePaymentSuccessRequest\x1a*.subscription.v1.HandlePaymentSuccessReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/subscription/payment/success\x12\x8e\x01\n" +
	"\x12CancelSubscription\x12*.subscription.v1.CancelSubscriptionRequest\x1a(.subscription.v1.CancelSubscriptionReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/subscription/cancel\x12\x8a\x01\n" +
	"\x11PauseSubscription\x12).subscription.v1.PauseSubscriptionRequest\x1a'.subscription.v1.PauseSubscriptionReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/subscription/pause\x12\x8e\x01\n" +
	"\x12ResumeSubscription\x12*.subscription.v1.ResumeSubscriptionRequest\x1a(.subscription.v1.ResumeSubscriptionReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/subscription/resume\x12\x9e\x01\n" +
	"\x16GetSubscriptionHistory\x12..subscription.v1.GetSubscriptionHistoryRequest\x1a,.subscription.v1.GetSubscriptionHistoryReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/subscription/history/{uid}\x12\x80\x01\n" +
	"\fSetAutoRenew\x12$.subscription.v1.SetAutoRenewRequest\x1a\".subscription.v1.SetAutoRenewReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/subscription/auto-renew\x12\x9f\x01\n" +
	"\x18GetExpiringSubscriptions\x120.subscription.v1.GetExpiringSubscriptionsRequest\x1a..subscription.v1.GetExpiringSubscriptionsReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/subscription/expiring\x12\xae\x01\n" +
	"\x1aUpdateExpiredSubscriptions\x122.subscription.v1.UpdateExpiredSubscriptionsRequest\x1a0.subscription.v1.UpdateExpiredSubscriptionsReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/subscription/expired/update\x12\x9d\x01\n" +
	"\x13ProcessAutoRenewals\x12+.subscription.v1.ProcessAutoRenewalsRequest\x1a).subscription.v1.ProcessAutoRenewalsReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/subscription/auto-renew/processB:Z8xinyuan_tech/subscription-service/api/subscription/v1;v1b\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_subscription_proto_goTypes = []any{
	(*Plan)(nil),                              // 0: subscription.v1.Plan
	(*ListPlansRequest)(nil),                  // 1: subscription.v1.ListPlansRequest
	(*ListPlansReply)(nil),                    // 2: subscription.v1.ListPlansReply
	(*GetMySubscriptionRequest)(nil),          // 3: subscription.v1.GetMySubscriptionRequest
	(*GetMySubscriptionReply)(nil),            // 4: subscription.v1.GetMySubscriptionReply
	(*CreateSubscriptionOrderRequest)(nil),    // 5: subscription.v1.CreateSubscriptionOrderRequest
	(*CreateSubscriptionOrderReply)(nil),      // 6: subscription.v1.CreateSubscriptionOrderReply
	(*HandlePaymentSuccessRequest)(nil),       // 7: subscription.v1.HandlePaymentSuccessRequest
	(*HandlePaymentSuccessReply)(nil),         // 8: subscription.v1.HandlePaymentSuccessReply
	(*CancelSubscriptionRequest)(nil),         // 9: subscription.v1.CancelSubscriptionRequest
	(*CancelSubscriptionReply)(nil),           // 10: subscription.v1.CancelSubscriptionReply
	(*PauseSubscriptionRequest)(nil),          // 11: subscription.v1.PauseSubscriptionRequest
	(*PauseSubscriptionReply)(nil),            // 12: subscription.v1.PauseSubscriptionReply
	(*ResumeSubscriptionRequest)(nil),         // 13: subscription.v1.ResumeSubscriptionRequest
	(*ResumeSubscriptionReply)(nil),           // 14: subscription.v1.ResumeSubscriptionReply
	(*SubscriptionHistoryItem)(nil),           // 15: subscription.v1.SubscriptionHistoryItem
	(*GetSubscriptionHistoryRequest)(nil),     // 16: subscription.v1.GetSubscriptionHistoryRequest
	(*GetSubscriptionHistoryReply)(nil),       // 17: subscription.v1.GetSubscriptionHistoryReply
	(*SetAutoRenewRequest)(nil),               // 18: subscription.v1.SetAutoRenewRequest
	(*SetAutoRenewReply)(nil),                 // 19: subscription.v1.SetAutoRenewReply
	(*GetExpiringSubscriptionsRequest)(nil),   // 20: subscription.v1.GetExpiringSubscriptionsRequest
	(*SubscriptionInfo)(nil),                  // 21: subscription.v1.SubscriptionInfo
	(*GetExpiringSubscriptionsReply)(nil),     // 22: subscription.v1.GetExpiringSubscriptionsReply
	(*UpdateExpiredSubscriptionsRequest)(nil), // 23: subscription.v1.UpdateExpiredSubscriptionsRequest
	(*UpdateExpiredSubscriptionsReply)(nil),   // 24: subscription.v1.UpdateExpiredSubscriptionsReply
	(*ProcessAutoRenewalsRequest)(nil),        // 25: subscription.v1.ProcessAutoRenewalsRequest
	(*AutoRenewResult)(nil),                   // 26: subscription.v1.AutoRenewResult
	(*ProcessAutoRenewalsReply)(nil),          // 27: subscription.v1.ProcessAutoRenewalsReply
}
var file_subscription_proto_depIdxs = []int32{
	0,  // 0: subscription.v1.ListPlansReply.plans:type_name -> subscription.v1.Plan
	15, // 1: subscription.v1.GetSubscriptionHistoryReply.items:type_name -> subscription.v1.SubscriptionHistoryItem
	21, // 2: subscription.v1.GetExpiringSubscriptionsReply.subscriptions:type_name -> subscription.v1.SubscriptionInfo
	26, // 3: subscription.v1.ProcessAutoRenewalsReply.results:type_name -> subscription.v1.AutoRenewResult
	1,  // 4: subscription.v1.Subscription.ListPlans:input_type -> subscription.v1.ListPlansRequest
	3,  // 5: subscription.v1.Subscription.GetMySubscription:input_type -> subscription.v1.GetMySubscriptionRequest
	5,  // 6: subscription.v1.Subscription.CreateSubscriptionOrder:input_type -> subscription.v1.CreateSubscriptionOrderRequest
	7,  // 7: subscription.v1.Subscription.HandlePaymentSuccess:input_type -> subscription.v1.HandlePaymentSuccessRequest
	9,  // 8: subscription.v1.Subscription.CancelSubscription:input_type -> subscription.v1.CancelSubscriptionRequest
	11, // 9: subscription.v1.Subscription.PauseSubscription:input_type -> subscription.v1.PauseSubscriptionRequest
	13, // 10: subscription.v1.Subscription.ResumeSubscription:input_type -> subscription.v1.ResumeSubscriptionRequest
	16, // 11: subscription.v1.Subscription.GetSubscriptionHistory:input_type -> subscription.v1.GetSubscriptionHistoryRequest
	18, // 12: subscription.v1.Subscription.SetAutoRenew:input_type -> subscription.v1.SetAutoRenewRequest
	20, // 13: subscription.v1.Subscription.GetExpiringSubscriptions:input_type -> subscription.v1.GetExpiringSubscriptionsRequest
	23, // 14: subscription.v1.Subscription.UpdateExpiredSubscriptions:input_type -> subscription.v1.UpdateExpiredSubscriptionsRequest
	25, // 15: subscription.v1.Subscription.ProcessAutoRenewals:input_type -> subscription.v1.ProcessAutoRenewalsRequest
	2,  // 16: subscription.v1.Subscription.ListPlans:output_type -> subscription.v1.ListPlansReply
	4,  // 17: subscription.v1.Subscription.GetMySubscription:output_type -> subscription.v1.GetMySubscriptionReply
	6,  // 18: subscription.v1.Subscription.CreateSubscriptionOrder:output_type -> subscription.v1.CreateSubscriptionOrderReply
	8,  // 19: subscription.v1.Subscription.HandlePaymentSuccess:output_type -> subscription.v1.HandlePaymentSuccessReply
	10, // 20: subscription.v1.Subscription.CancelSubscription:output_type -> subscription.v1.CancelSubscriptionReply
	12, // 21: subscription.v1.Subscription.PauseSubscription:output_type -> subscription.v1.PauseSubscriptionReply
	14, // 22: subscription.v1.Subscription.ResumeSubscription:output_type -> subscription.v1.ResumeSubscriptionReply
	17, // 23: subscription.v1.Subscription.GetSubscriptionHistory:output_type -> subscription.v1.GetSubscriptionHistoryReply
	19, // 24: subscription.v1.Subscription.SetAutoRenew:output_type -> subscription.v1.SetAutoRenewReply
	22, // 25: subscription.v1.Subscription.GetExpiringSubscriptions:output_type -> subscription.v1.GetExpiringSubscriptionsReply
	24, // 26: subscription.v1.Subscription.UpdateExpiredSubscriptions:output_type -> subscription.v1.UpdateExpiredSubscriptionsReply
	27, // 27: subscription.v1.Subscription.ProcessAutoRenewals:output_type -> subscription.v1.ProcessAutoRenewalsReply
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
