// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/subscription/v1/subscription.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Plan with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Plan) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Plan with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PlanMultiError, or nil if none found.
func (m *Plan) ValidateAll() error {
	return m.validate(true)
}

func (m *Plan) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Price

	// no validation rules for Currency

	// no validation rules for DurationDays

	// no validation rules for Type

	if len(errors) > 0 {
		return PlanMultiError(errors)
	}

	return nil
}

// PlanMultiError is an error wrapping multiple validation errors returned by
// Plan.ValidateAll() if the designated constraints aren't met.
type PlanMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PlanMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PlanMultiError) AllErrors() []error { return m }

// PlanValidationError is the validation error returned by Plan.Validate if the
// designated constraints aren't met.
type PlanValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PlanValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PlanValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PlanValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PlanValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PlanValidationError) ErrorName() string { return "PlanValidationError" }

// Error satisfies the builtin error interface
func (e PlanValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPlan.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PlanValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PlanValidationError{}

// Validate checks the field values on ListPlansRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListPlansRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPlansRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPlansRequestMultiError, or nil if none found.
func (m *ListPlansRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPlansRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListPlansRequestMultiError(errors)
	}

	return nil
}

// ListPlansRequestMultiError is an error wrapping multiple validation errors
// returned by ListPlansRequest.ValidateAll() if the designated constraints
// aren't met.
type ListPlansRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPlansRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPlansRequestMultiError) AllErrors() []error { return m }

// ListPlansRequestValidationError is the validation error returned by
// ListPlansRequest.Validate if the designated constraints aren't met.
type ListPlansRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPlansRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPlansRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPlansRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPlansRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPlansRequestValidationError) ErrorName() string { return "ListPlansRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListPlansRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPlansRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPlansRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPlansRequestValidationError{}

// Validate checks the field values on ListPlansReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListPlansReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPlansReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListPlansReplyMultiError,
// or nil if none found.
func (m *ListPlansReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPlansReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPlans() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPlansReplyValidationError{
						field:  fmt.Sprintf("Plans[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPlansReplyValidationError{
						field:  fmt.Sprintf("Plans[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPlansReplyValidationError{
					field:  fmt.Sprintf("Plans[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListPlansReplyMultiError(errors)
	}

	return nil
}

// ListPlansReplyMultiError is an error wrapping multiple validation errors
// returned by ListPlansReply.ValidateAll() if the designated constraints
// aren't met.
type ListPlansReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPlansReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPlansReplyMultiError) AllErrors() []error { return m }

// ListPlansReplyValidationError is the validation error returned by
// ListPlansReply.Validate if the designated constraints aren't met.
type ListPlansReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPlansReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPlansReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPlansReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPlansReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPlansReplyValidationError) ErrorName() string { return "ListPlansReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListPlansReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPlansReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPlansReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPlansReplyValidationError{}

// Validate checks the field values on GetMySubscriptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMySubscriptionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMySubscriptionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMySubscriptionRequestMultiError, or nil if none found.
func (m *GetMySubscriptionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMySubscriptionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUid() <= 0 {
		err := GetMySubscriptionRequestValidationError{
			field:  "Uid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetMySubscriptionRequestMultiError(errors)
	}

	return nil
}

// GetMySubscriptionRequestMultiError is an error wrapping multiple validation
// errors returned by GetMySubscriptionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetMySubscriptionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMySubscriptionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMySubscriptionRequestMultiError) AllErrors() []error { return m }

// GetMySubscriptionRequestValidationError is the validation error returned by
// GetMySubscriptionRequest.Validate if the designated constraints aren't met.
type GetMySubscriptionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMySubscriptionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMySubscriptionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMySubscriptionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMySubscriptionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMySubscriptionRequestValidationError) ErrorName() string {
	return "GetMySubscriptionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetMySubscriptionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMySubscriptionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMySubscriptionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMySubscriptionRequestValidationError{}

// Validate checks the field values on GetMySubscriptionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMySubscriptionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMySubscriptionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMySubscriptionReplyMultiError, or nil if none found.
func (m *GetMySubscriptionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMySubscriptionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsActive

	// no validation rules for PlanId

	// no validation rules for StartTime

	// no validation rules for EndTime

	// no validation rules for Status

	// no validation rules for AutoRenew

	if len(errors) > 0 {
		return GetMySubscriptionReplyMultiError(errors)
	}

	return nil
}

// GetMySubscriptionReplyMultiError is an error wrapping multiple validation
// errors returned by GetMySubscriptionReply.ValidateAll() if the designated
// constraints aren't met.
type GetMySubscriptionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMySubscriptionReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMySubscriptionReplyMultiError) AllErrors() []error { return m }

// GetMySubscriptionReplyValidationError is the validation error returned by
// GetMySubscriptionReply.Validate if the designated constraints aren't met.
type GetMySubscriptionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMySubscriptionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMySubscriptionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMySubscriptionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMySubscriptionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMySubscriptionReplyValidationError) ErrorName() string {
	return "GetMySubscriptionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetMySubscriptionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMySubscriptionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMySubscriptionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMySubscriptionReplyValidationError{}

// Validate checks the field values on CreateSubscriptionOrderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSubscriptionOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSubscriptionOrderRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateSubscriptionOrderRequestMultiError, or nil if none found.
func (m *CreateSubscriptionOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSubscriptionOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUid() <= 0 {
		err := CreateSubscriptionOrderRequestValidationError{
			field:  "Uid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetPlanId()); l < 1 || l > 50 {
		err := CreateSubscriptionOrderRequestValidationError{
			field:  "PlanId",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateSubscriptionOrderRequest_PaymentMethod_InLookup[m.GetPaymentMethod()]; !ok {
		err := CreateSubscriptionOrderRequestValidationError{
			field:  "PaymentMethod",
			reason: "value must be in list [alipay wechatpay]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateSubscriptionOrderRequestMultiError(errors)
	}

	return nil
}

// CreateSubscriptionOrderRequestMultiError is an error wrapping multiple
// validation errors returned by CreateSubscriptionOrderRequest.ValidateAll()
// if the designated constraints aren't met.
type CreateSubscriptionOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSubscriptionOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSubscriptionOrderRequestMultiError) AllErrors() []error { return m }

// CreateSubscriptionOrderRequestValidationError is the validation error
// returned by CreateSubscriptionOrderRequest.Validate if the designated
// constraints aren't met.
type CreateSubscriptionOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSubscriptionOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSubscriptionOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSubscriptionOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSubscriptionOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSubscriptionOrderRequestValidationError) ErrorName() string {
	return "CreateSubscriptionOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSubscriptionOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSubscriptionOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSubscriptionOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSubscriptionOrderRequestValidationError{}

var _CreateSubscriptionOrderRequest_PaymentMethod_InLookup = map[string]struct{}{
	"alipay":    {},
	"wechatpay": {},
}

// Validate checks the field values on CreateSubscriptionOrderReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSubscriptionOrderReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSubscriptionOrderReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSubscriptionOrderReplyMultiError, or nil if none found.
func (m *CreateSubscriptionOrderReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSubscriptionOrderReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderId

	// no validation rules for PaymentId

	// no validation rules for PayUrl

	// no validation rules for PayCode

	// no validation rules for PayParams

	if len(errors) > 0 {
		return CreateSubscriptionOrderReplyMultiError(errors)
	}

	return nil
}

// CreateSubscriptionOrderReplyMultiError is an error wrapping multiple
// validation errors returned by CreateSubscriptionOrderReply.ValidateAll() if
// the designated constraints aren't met.
type CreateSubscriptionOrderReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSubscriptionOrderReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSubscriptionOrderReplyMultiError) AllErrors() []error { return m }

// CreateSubscriptionOrderReplyValidationError is the validation error returned
// by CreateSubscriptionOrderReply.Validate if the designated constraints
// aren't met.
type CreateSubscriptionOrderReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSubscriptionOrderReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSubscriptionOrderReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSubscriptionOrderReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSubscriptionOrderReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSubscriptionOrderReplyValidationError) ErrorName() string {
	return "CreateSubscriptionOrderReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSubscriptionOrderReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSubscriptionOrderReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSubscriptionOrderReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSubscriptionOrderReplyValidationError{}

// Validate checks the field values on HandlePaymentSuccessRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HandlePaymentSuccessRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HandlePaymentSuccessRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HandlePaymentSuccessRequestMultiError, or nil if none found.
func (m *HandlePaymentSuccessRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HandlePaymentSuccessRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetOrderId()); l < 1 || l > 100 {
		err := HandlePaymentSuccessRequestValidationError{
			field:  "OrderId",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetPaymentId()); l < 1 || l > 100 {
		err := HandlePaymentSuccessRequestValidationError{
			field:  "PaymentId",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := HandlePaymentSuccessRequestValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return HandlePaymentSuccessRequestMultiError(errors)
	}

	return nil
}

// HandlePaymentSuccessRequestMultiError is an error wrapping multiple
// validation errors returned by HandlePaymentSuccessRequest.ValidateAll() if
// the designated constraints aren't met.
type HandlePaymentSuccessRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HandlePaymentSuccessRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HandlePaymentSuccessRequestMultiError) AllErrors() []error { return m }

// HandlePaymentSuccessRequestValidationError is the validation error returned
// by HandlePaymentSuccessRequest.Validate if the designated constraints
// aren't met.
type HandlePaymentSuccessRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HandlePaymentSuccessRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HandlePaymentSuccessRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HandlePaymentSuccessRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HandlePaymentSuccessRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HandlePaymentSuccessRequestValidationError) ErrorName() string {
	return "HandlePaymentSuccessRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HandlePaymentSuccessRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHandlePaymentSuccessRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HandlePaymentSuccessRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HandlePaymentSuccessRequestValidationError{}

// Validate checks the field values on HandlePaymentSuccessReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HandlePaymentSuccessReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HandlePaymentSuccessReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HandlePaymentSuccessReplyMultiError, or nil if none found.
func (m *HandlePaymentSuccessReply) ValidateAll() error {
	return m.validate(true)
}

func (m *HandlePaymentSuccessReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return HandlePaymentSuccessReplyMultiError(errors)
	}

	return nil
}

// HandlePaymentSuccessReplyMultiError is an error wrapping multiple validation
// errors returned by HandlePaymentSuccessReply.ValidateAll() if the
// designated constraints aren't met.
type HandlePaymentSuccessReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HandlePaymentSuccessReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HandlePaymentSuccessReplyMultiError) AllErrors() []error { return m }

// HandlePaymentSuccessReplyValidationError is the validation error returned by
// HandlePaymentSuccessReply.Validate if the designated constraints aren't met.
type HandlePaymentSuccessReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HandlePaymentSuccessReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HandlePaymentSuccessReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HandlePaymentSuccessReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HandlePaymentSuccessReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HandlePaymentSuccessReplyValidationError) ErrorName() string {
	return "HandlePaymentSuccessReplyValidationError"
}

// Error satisfies the builtin error interface
func (e HandlePaymentSuccessReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHandlePaymentSuccessReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HandlePaymentSuccessReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HandlePaymentSuccessReplyValidationError{}

// Validate checks the field values on CancelSubscriptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelSubscriptionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelSubscriptionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelSubscriptionRequestMultiError, or nil if none found.
func (m *CancelSubscriptionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelSubscriptionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUid() <= 0 {
		err := CancelSubscriptionRequestValidationError{
			field:  "Uid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Reason

	if len(errors) > 0 {
		return CancelSubscriptionRequestMultiError(errors)
	}

	return nil
}

// CancelSubscriptionRequestMultiError is an error wrapping multiple validation
// errors returned by CancelSubscriptionRequest.ValidateAll() if the
// designated constraints aren't met.
type CancelSubscriptionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelSubscriptionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelSubscriptionRequestMultiError) AllErrors() []error { return m }

// CancelSubscriptionRequestValidationError is the validation error returned by
// CancelSubscriptionRequest.Validate if the designated constraints aren't met.
type CancelSubscriptionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelSubscriptionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelSubscriptionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelSubscriptionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelSubscriptionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelSubscriptionRequestValidationError) ErrorName() string {
	return "CancelSubscriptionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CancelSubscriptionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelSubscriptionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelSubscriptionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelSubscriptionRequestValidationError{}

// Validate checks the field values on CancelSubscriptionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelSubscriptionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelSubscriptionReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelSubscriptionReplyMultiError, or nil if none found.
func (m *CancelSubscriptionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelSubscriptionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return CancelSubscriptionReplyMultiError(errors)
	}

	return nil
}

// CancelSubscriptionReplyMultiError is an error wrapping multiple validation
// errors returned by CancelSubscriptionReply.ValidateAll() if the designated
// constraints aren't met.
type CancelSubscriptionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelSubscriptionReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelSubscriptionReplyMultiError) AllErrors() []error { return m }

// CancelSubscriptionReplyValidationError is the validation error returned by
// CancelSubscriptionReply.Validate if the designated constraints aren't met.
type CancelSubscriptionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelSubscriptionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelSubscriptionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelSubscriptionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelSubscriptionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelSubscriptionReplyValidationError) ErrorName() string {
	return "CancelSubscriptionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CancelSubscriptionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelSubscriptionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelSubscriptionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelSubscriptionReplyValidationError{}

// Validate checks the field values on PauseSubscriptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PauseSubscriptionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PauseSubscriptionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PauseSubscriptionRequestMultiError, or nil if none found.
func (m *PauseSubscriptionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PauseSubscriptionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUid() <= 0 {
		err := PauseSubscriptionRequestValidationError{
			field:  "Uid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Reason

	if len(errors) > 0 {
		return PauseSubscriptionRequestMultiError(errors)
	}

	return nil
}

// PauseSubscriptionRequestMultiError is an error wrapping multiple validation
// errors returned by PauseSubscriptionRequest.ValidateAll() if the designated
// constraints aren't met.
type PauseSubscriptionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PauseSubscriptionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PauseSubscriptionRequestMultiError) AllErrors() []error { return m }

// PauseSubscriptionRequestValidationError is the validation error returned by
// PauseSubscriptionRequest.Validate if the designated constraints aren't met.
type PauseSubscriptionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PauseSubscriptionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PauseSubscriptionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PauseSubscriptionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PauseSubscriptionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PauseSubscriptionRequestValidationError) ErrorName() string {
	return "PauseSubscriptionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PauseSubscriptionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPauseSubscriptionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PauseSubscriptionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PauseSubscriptionRequestValidationError{}

// Validate checks the field values on PauseSubscriptionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PauseSubscriptionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PauseSubscriptionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PauseSubscriptionReplyMultiError, or nil if none found.
func (m *PauseSubscriptionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PauseSubscriptionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return PauseSubscriptionReplyMultiError(errors)
	}

	return nil
}

// PauseSubscriptionReplyMultiError is an error wrapping multiple validation
// errors returned by PauseSubscriptionReply.ValidateAll() if the designated
// constraints aren't met.
type PauseSubscriptionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PauseSubscriptionReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PauseSubscriptionReplyMultiError) AllErrors() []error { return m }

// PauseSubscriptionReplyValidationError is the validation error returned by
// PauseSubscriptionReply.Validate if the designated constraints aren't met.
type PauseSubscriptionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PauseSubscriptionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PauseSubscriptionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PauseSubscriptionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PauseSubscriptionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PauseSubscriptionReplyValidationError) ErrorName() string {
	return "PauseSubscriptionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PauseSubscriptionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPauseSubscriptionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PauseSubscriptionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PauseSubscriptionReplyValidationError{}

// Validate checks the field values on ResumeSubscriptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResumeSubscriptionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResumeSubscriptionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResumeSubscriptionRequestMultiError, or nil if none found.
func (m *ResumeSubscriptionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResumeSubscriptionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUid() <= 0 {
		err := ResumeSubscriptionRequestValidationError{
			field:  "Uid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ResumeSubscriptionRequestMultiError(errors)
	}

	return nil
}

// ResumeSubscriptionRequestMultiError is an error wrapping multiple validation
// errors returned by ResumeSubscriptionRequest.ValidateAll() if the
// designated constraints aren't met.
type ResumeSubscriptionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResumeSubscriptionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResumeSubscriptionRequestMultiError) AllErrors() []error { return m }

// ResumeSubscriptionRequestValidationError is the validation error returned by
// ResumeSubscriptionRequest.Validate if the designated constraints aren't met.
type ResumeSubscriptionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResumeSubscriptionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResumeSubscriptionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResumeSubscriptionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResumeSubscriptionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResumeSubscriptionRequestValidationError) ErrorName() string {
	return "ResumeSubscriptionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResumeSubscriptionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResumeSubscriptionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResumeSubscriptionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResumeSubscriptionRequestValidationError{}

// Validate checks the field values on ResumeSubscriptionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResumeSubscriptionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResumeSubscriptionReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResumeSubscriptionReplyMultiError, or nil if none found.
func (m *ResumeSubscriptionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ResumeSubscriptionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return ResumeSubscriptionReplyMultiError(errors)
	}

	return nil
}

// ResumeSubscriptionReplyMultiError is an error wrapping multiple validation
// errors returned by ResumeSubscriptionReply.ValidateAll() if the designated
// constraints aren't met.
type ResumeSubscriptionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResumeSubscriptionReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResumeSubscriptionReplyMultiError) AllErrors() []error { return m }

// ResumeSubscriptionReplyValidationError is the validation error returned by
// ResumeSubscriptionReply.Validate if the designated constraints aren't met.
type ResumeSubscriptionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResumeSubscriptionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResumeSubscriptionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResumeSubscriptionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResumeSubscriptionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResumeSubscriptionReplyValidationError) ErrorName() string {
	return "ResumeSubscriptionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ResumeSubscriptionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResumeSubscriptionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResumeSubscriptionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResumeSubscriptionReplyValidationError{}

// Validate checks the field values on SubscriptionHistoryItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubscriptionHistoryItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubscriptionHistoryItem with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubscriptionHistoryItemMultiError, or nil if none found.
func (m *SubscriptionHistoryItem) ValidateAll() error {
	return m.validate(true)
}

func (m *SubscriptionHistoryItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for PlanId

	// no validation rules for PlanName

	// no validation rules for StartTime

	// no validation rules for EndTime

	// no validation rules for Status

	// no validation rules for Action

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return SubscriptionHistoryItemMultiError(errors)
	}

	return nil
}

// SubscriptionHistoryItemMultiError is an error wrapping multiple validation
// errors returned by SubscriptionHistoryItem.ValidateAll() if the designated
// constraints aren't met.
type SubscriptionHistoryItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscriptionHistoryItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscriptionHistoryItemMultiError) AllErrors() []error { return m }

// SubscriptionHistoryItemValidationError is the validation error returned by
// SubscriptionHistoryItem.Validate if the designated constraints aren't met.
type SubscriptionHistoryItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscriptionHistoryItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscriptionHistoryItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscriptionHistoryItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscriptionHistoryItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscriptionHistoryItemValidationError) ErrorName() string {
	return "SubscriptionHistoryItemValidationError"
}

// Error satisfies the builtin error interface
func (e SubscriptionHistoryItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscriptionHistoryItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscriptionHistoryItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscriptionHistoryItemValidationError{}

// Validate checks the field values on GetSubscriptionHistoryRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubscriptionHistoryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubscriptionHistoryRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetSubscriptionHistoryRequestMultiError, or nil if none found.
func (m *GetSubscriptionHistoryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubscriptionHistoryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUid() <= 0 {
		err := GetSubscriptionHistoryRequestValidationError{
			field:  "Uid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetSubscriptionHistoryRequestMultiError(errors)
	}

	return nil
}

// GetSubscriptionHistoryRequestMultiError is an error wrapping multiple
// validation errors returned by GetSubscriptionHistoryRequest.ValidateAll()
// if the designated constraints aren't met.
type GetSubscriptionHistoryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubscriptionHistoryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubscriptionHistoryRequestMultiError) AllErrors() []error { return m }

// GetSubscriptionHistoryRequestValidationError is the validation error
// returned by GetSubscriptionHistoryRequest.Validate if the designated
// constraints aren't met.
type GetSubscriptionHistoryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubscriptionHistoryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubscriptionHistoryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubscriptionHistoryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubscriptionHistoryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubscriptionHistoryRequestValidationError) ErrorName() string {
	return "GetSubscriptionHistoryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubscriptionHistoryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubscriptionHistoryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubscriptionHistoryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubscriptionHistoryRequestValidationError{}

// Validate checks the field values on GetSubscriptionHistoryReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubscriptionHistoryReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubscriptionHistoryReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubscriptionHistoryReplyMultiError, or nil if none found.
func (m *GetSubscriptionHistoryReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubscriptionHistoryReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetSubscriptionHistoryReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetSubscriptionHistoryReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetSubscriptionHistoryReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetSubscriptionHistoryReplyMultiError(errors)
	}

	return nil
}

// GetSubscriptionHistoryReplyMultiError is an error wrapping multiple
// validation errors returned by GetSubscriptionHistoryReply.ValidateAll() if
// the designated constraints aren't met.
type GetSubscriptionHistoryReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubscriptionHistoryReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubscriptionHistoryReplyMultiError) AllErrors() []error { return m }

// GetSubscriptionHistoryReplyValidationError is the validation error returned
// by GetSubscriptionHistoryReply.Validate if the designated constraints
// aren't met.
type GetSubscriptionHistoryReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubscriptionHistoryReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubscriptionHistoryReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubscriptionHistoryReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubscriptionHistoryReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubscriptionHistoryReplyValidationError) ErrorName() string {
	return "GetSubscriptionHistoryReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubscriptionHistoryReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubscriptionHistoryReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubscriptionHistoryReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubscriptionHistoryReplyValidationError{}

// Validate checks the field values on SetAutoRenewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetAutoRenewRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetAutoRenewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetAutoRenewRequestMultiError, or nil if none found.
func (m *SetAutoRenewRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetAutoRenewRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUid() <= 0 {
		err := SetAutoRenewRequestValidationError{
			field:  "Uid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for AutoRenew

	if len(errors) > 0 {
		return SetAutoRenewRequestMultiError(errors)
	}

	return nil
}

// SetAutoRenewRequestMultiError is an error wrapping multiple validation
// errors returned by SetAutoRenewRequest.ValidateAll() if the designated
// constraints aren't met.
type SetAutoRenewRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetAutoRenewRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetAutoRenewRequestMultiError) AllErrors() []error { return m }

// SetAutoRenewRequestValidationError is the validation error returned by
// SetAutoRenewRequest.Validate if the designated constraints aren't met.
type SetAutoRenewRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetAutoRenewRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetAutoRenewRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetAutoRenewRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetAutoRenewRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetAutoRenewRequestValidationError) ErrorName() string {
	return "SetAutoRenewRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetAutoRenewRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetAutoRenewRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetAutoRenewRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetAutoRenewRequestValidationError{}

// Validate checks the field values on SetAutoRenewReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SetAutoRenewReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetAutoRenewReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetAutoRenewReplyMultiError, or nil if none found.
func (m *SetAutoRenewReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SetAutoRenewReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return SetAutoRenewReplyMultiError(errors)
	}

	return nil
}

// SetAutoRenewReplyMultiError is an error wrapping multiple validation errors
// returned by SetAutoRenewReply.ValidateAll() if the designated constraints
// aren't met.
type SetAutoRenewReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetAutoRenewReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetAutoRenewReplyMultiError) AllErrors() []error { return m }

// SetAutoRenewReplyValidationError is the validation error returned by
// SetAutoRenewReply.Validate if the designated constraints aren't met.
type SetAutoRenewReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetAutoRenewReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetAutoRenewReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetAutoRenewReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetAutoRenewReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetAutoRenewReplyValidationError) ErrorName() string {
	return "SetAutoRenewReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SetAutoRenewReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetAutoRenewReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetAutoRenewReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetAutoRenewReplyValidationError{}

// Validate checks the field values on GetExpiringSubscriptionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetExpiringSubscriptionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetExpiringSubscriptionsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetExpiringSubscriptionsRequestMultiError, or nil if none found.
func (m *GetExpiringSubscriptionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetExpiringSubscriptionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetDaysBeforeExpiry(); val < 1 || val > 30 {
		err := GetExpiringSubscriptionsRequestValidationError{
			field:  "DaysBeforeExpiry",
			reason: "value must be inside range [1, 30]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetExpiringSubscriptionsRequestMultiError(errors)
	}

	return nil
}

// GetExpiringSubscriptionsRequestMultiError is an error wrapping multiple
// validation errors returned by GetExpiringSubscriptionsRequest.ValidateAll()
// if the designated constraints aren't met.
type GetExpiringSubscriptionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetExpiringSubscriptionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetExpiringSubscriptionsRequestMultiError) AllErrors() []error { return m }

// GetExpiringSubscriptionsRequestValidationError is the validation error
// returned by GetExpiringSubscriptionsRequest.Validate if the designated
// constraints aren't met.
type GetExpiringSubscriptionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetExpiringSubscriptionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetExpiringSubscriptionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetExpiringSubscriptionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetExpiringSubscriptionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetExpiringSubscriptionsRequestValidationError) ErrorName() string {
	return "GetExpiringSubscriptionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetExpiringSubscriptionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetExpiringSubscriptionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetExpiringSubscriptionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetExpiringSubscriptionsRequestValidationError{}

// Validate checks the field values on SubscriptionInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SubscriptionInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubscriptionInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubscriptionInfoMultiError, or nil if none found.
func (m *SubscriptionInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SubscriptionInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uid

	// no validation rules for PlanId

	// no validation rules for PlanName

	// no validation rules for StartTime

	// no validation rules for EndTime

	// no validation rules for AutoRenew

	// no validation rules for Amount

	if len(errors) > 0 {
		return SubscriptionInfoMultiError(errors)
	}

	return nil
}

// SubscriptionInfoMultiError is an error wrapping multiple validation errors
// returned by SubscriptionInfo.ValidateAll() if the designated constraints
// aren't met.
type SubscriptionInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscriptionInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscriptionInfoMultiError) AllErrors() []error { return m }

// SubscriptionInfoValidationError is the validation error returned by
// SubscriptionInfo.Validate if the designated constraints aren't met.
type SubscriptionInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscriptionInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscriptionInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscriptionInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscriptionInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscriptionInfoValidationError) ErrorName() string { return "SubscriptionInfoValidationError" }

// Error satisfies the builtin error interface
func (e SubscriptionInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscriptionInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscriptionInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscriptionInfoValidationError{}

// Validate checks the field values on GetExpiringSubscriptionsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetExpiringSubscriptionsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetExpiringSubscriptionsReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetExpiringSubscriptionsReplyMultiError, or nil if none found.
func (m *GetExpiringSubscriptionsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetExpiringSubscriptionsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSubscriptions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetExpiringSubscriptionsReplyValidationError{
						field:  fmt.Sprintf("Subscriptions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetExpiringSubscriptionsReplyValidationError{
						field:  fmt.Sprintf("Subscriptions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetExpiringSubscriptionsReplyValidationError{
					field:  fmt.Sprintf("Subscriptions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetExpiringSubscriptionsReplyMultiError(errors)
	}

	return nil
}

// GetExpiringSubscriptionsReplyMultiError is an error wrapping multiple
// validation errors returned by GetExpiringSubscriptionsReply.ValidateAll()
// if the designated constraints aren't met.
type GetExpiringSubscriptionsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetExpiringSubscriptionsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetExpiringSubscriptionsReplyMultiError) AllErrors() []error { return m }

// GetExpiringSubscriptionsReplyValidationError is the validation error
// returned by GetExpiringSubscriptionsReply.Validate if the designated
// constraints aren't met.
type GetExpiringSubscriptionsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetExpiringSubscriptionsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetExpiringSubscriptionsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetExpiringSubscriptionsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetExpiringSubscriptionsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetExpiringSubscriptionsReplyValidationError) ErrorName() string {
	return "GetExpiringSubscriptionsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetExpiringSubscriptionsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetExpiringSubscriptionsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetExpiringSubscriptionsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetExpiringSubscriptionsReplyValidationError{}

// Validate checks the field values on UpdateExpiredSubscriptionsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateExpiredSubscriptionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateExpiredSubscriptionsRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateExpiredSubscriptionsRequestMultiError, or nil if none found.
func (m *UpdateExpiredSubscriptionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateExpiredSubscriptionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateExpiredSubscriptionsRequestMultiError(errors)
	}

	return nil
}

// UpdateExpiredSubscriptionsRequestMultiError is an error wrapping multiple
// validation errors returned by
// UpdateExpiredSubscriptionsRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateExpiredSubscriptionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateExpiredSubscriptionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateExpiredSubscriptionsRequestMultiError) AllErrors() []error { return m }

// UpdateExpiredSubscriptionsRequestValidationError is the validation error
// returned by UpdateExpiredSubscriptionsRequest.Validate if the designated
// constraints aren't met.
type UpdateExpiredSubscriptionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateExpiredSubscriptionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateExpiredSubscriptionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateExpiredSubscriptionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateExpiredSubscriptionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateExpiredSubscriptionsRequestValidationError) ErrorName() string {
	return "UpdateExpiredSubscriptionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateExpiredSubscriptionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateExpiredSubscriptionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateExpiredSubscriptionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateExpiredSubscriptionsRequestValidationError{}

// Validate checks the field values on UpdateExpiredSubscriptionsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateExpiredSubscriptionsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateExpiredSubscriptionsReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateExpiredSubscriptionsReplyMultiError, or nil if none found.
func (m *UpdateExpiredSubscriptionsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateExpiredSubscriptionsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UpdatedCount

	if len(errors) > 0 {
		return UpdateExpiredSubscriptionsReplyMultiError(errors)
	}

	return nil
}

// UpdateExpiredSubscriptionsReplyMultiError is an error wrapping multiple
// validation errors returned by UpdateExpiredSubscriptionsReply.ValidateAll()
// if the designated constraints aren't met.
type UpdateExpiredSubscriptionsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateExpiredSubscriptionsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateExpiredSubscriptionsReplyMultiError) AllErrors() []error { return m }

// UpdateExpiredSubscriptionsReplyValidationError is the validation error
// returned by UpdateExpiredSubscriptionsReply.Validate if the designated
// constraints aren't met.
type UpdateExpiredSubscriptionsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateExpiredSubscriptionsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateExpiredSubscriptionsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateExpiredSubscriptionsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateExpiredSubscriptionsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateExpiredSubscriptionsReplyValidationError) ErrorName() string {
	return "UpdateExpiredSubscriptionsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateExpiredSubscriptionsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateExpiredSubscriptionsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateExpiredSubscriptionsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateExpiredSubscriptionsReplyValidationError{}

// Validate checks the field values on ProcessAutoRenewalsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProcessAutoRenewalsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProcessAutoRenewalsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProcessAutoRenewalsRequestMultiError, or nil if none found.
func (m *ProcessAutoRenewalsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProcessAutoRenewalsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetDaysBeforeExpiry(); val < 1 || val > 30 {
		err := ProcessAutoRenewalsRequestValidationError{
			field:  "DaysBeforeExpiry",
			reason: "value must be inside range [1, 30]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for DryRun

	if len(errors) > 0 {
		return ProcessAutoRenewalsRequestMultiError(errors)
	}

	return nil
}

// ProcessAutoRenewalsRequestMultiError is an error wrapping multiple
// validation errors returned by ProcessAutoRenewalsRequest.ValidateAll() if
// the designated constraints aren't met.
type ProcessAutoRenewalsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProcessAutoRenewalsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProcessAutoRenewalsRequestMultiError) AllErrors() []error { return m }

// ProcessAutoRenewalsRequestValidationError is the validation error returned
// by ProcessAutoRenewalsRequest.Validate if the designated constraints aren't met.
type ProcessAutoRenewalsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProcessAutoRenewalsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProcessAutoRenewalsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProcessAutoRenewalsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProcessAutoRenewalsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProcessAutoRenewalsRequestValidationError) ErrorName() string {
	return "ProcessAutoRenewalsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProcessAutoRenewalsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProcessAutoRenewalsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProcessAutoRenewalsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProcessAutoRenewalsRequestValidationError{}

// Validate checks the field values on AutoRenewResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AutoRenewResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AutoRenewResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AutoRenewResultMultiError, or nil if none found.
func (m *AutoRenewResult) ValidateAll() error {
	return m.validate(true)
}

func (m *AutoRenewResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uid

	// no validation rules for PlanId

	// no validation rules for Success

	// no validation rules for OrderId

	// no validation rules for PaymentId

	// no validation rules for ErrorMessage

	if len(errors) > 0 {
		return AutoRenewResultMultiError(errors)
	}

	return nil
}

// AutoRenewResultMultiError is an error wrapping multiple validation errors
// returned by AutoRenewResult.ValidateAll() if the designated constraints
// aren't met.
type AutoRenewResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AutoRenewResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AutoRenewResultMultiError) AllErrors() []error { return m }

// AutoRenewResultValidationError is the validation error returned by
// AutoRenewResult.Validate if the designated constraints aren't met.
type AutoRenewResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AutoRenewResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AutoRenewResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AutoRenewResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AutoRenewResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AutoRenewResultValidationError) ErrorName() string { return "AutoRenewResultValidationError" }

// Error satisfies the builtin error interface
func (e AutoRenewResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAutoRenewResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AutoRenewResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AutoRenewResultValidationError{}

// Validate checks the field values on ProcessAutoRenewalsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProcessAutoRenewalsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProcessAutoRenewalsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProcessAutoRenewalsReplyMultiError, or nil if none found.
func (m *ProcessAutoRenewalsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ProcessAutoRenewalsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalCount

	// no validation rules for SuccessCount

	// no validation rules for FailedCount

	for idx, item := range m.GetResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProcessAutoRenewalsReplyValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProcessAutoRenewalsReplyValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProcessAutoRenewalsReplyValidationError{
					field:  fmt.Sprintf("Results[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ProcessAutoRenewalsReplyMultiError(errors)
	}

	return nil
}

// ProcessAutoRenewalsReplyMultiError is an error wrapping multiple validation
// errors returned by ProcessAutoRenewalsReply.ValidateAll() if the designated
// constraints aren't met.
type ProcessAutoRenewalsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProcessAutoRenewalsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProcessAutoRenewalsReplyMultiError) AllErrors() []error { return m }

// ProcessAutoRenewalsReplyValidationError is the validation error returned by
// ProcessAutoRenewalsReply.Validate if the designated constraints aren't met.
type ProcessAutoRenewalsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProcessAutoRenewalsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProcessAutoRenewalsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProcessAutoRenewalsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProcessAutoRenewalsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProcessAutoRenewalsReplyValidationError) ErrorName() string {
	return "ProcessAutoRenewalsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ProcessAutoRenewalsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProcessAutoRenewalsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProcessAutoRenewalsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProcessAutoRenewalsReplyValidationError{}
