// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"os"
	"xinyuan_tech/subscription-service/internal/biz"
	"xinyuan_tech/subscription-service/internal/conf"
	"xinyuan_tech/subscription-service/internal/data"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp 初始化应用
func wireApp(bootstrap *conf.Bootstrap) (*CronApp, func(), error) {
	log := bootstrap.Log
	logger := newLogger(log)
	db := data.NewDB(bootstrap)
	dataData, cleanup, err := data.NewData(bootstrap, logger, db)
	if err != nil {
		return nil, nil, err
	}
	planRepo := data.NewPlanRepo(dataData, logger)
	userSubscriptionRepo := data.NewUserSubscriptionRepo(dataData, logger)
	subscriptionOrderRepo := data.NewSubscriptionOrderRepo(dataData, logger)
	subscriptionHistoryRepo := data.NewSubscriptionHistoryRepo(dataData, logger)
	paymentClient, err := data.NewPaymentClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	subscriptionUsecase := biz.NewSubscriptionUsecase(planRepo, userSubscriptionRepo, subscriptionOrderRepo, subscriptionHistoryRepo, paymentClient, logger)
	cronApp := &CronApp{
		subscriptionUsecase: subscriptionUsecase,
	}
	return cronApp, func() {
		cleanup()
	}, nil
}

// wire.go:

// CronApp Cron 应用结构
type CronApp struct {
	subscriptionUsecase *biz.SubscriptionUsecase
}

// newLogger 创建 logger
func newLogger(c *conf.Log) log.Logger {
	return log.With(log.NewStdLogger(os.Stdout), "ts", log.DefaultTimestamp, "caller", log.DefaultCaller, "service.name", "subscription-cron")
}
