// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"xinyuan_tech/subscription-service/internal/biz"
	"xinyuan_tech/subscription-service/internal/conf"
	"xinyuan_tech/subscription-service/internal/data"
	"xinyuan_tech/subscription-service/internal/server"
	"xinyuan_tech/subscription-service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(bootstrap)
	dataData, cleanup, err := data.NewData(bootstrap, logger, db)
	if err != nil {
		return nil, nil, err
	}
	subscriptionRepo := data.NewSubscriptionRepo(dataData, logger)
	paymentClient, err := data.NewPaymentClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	subscriptionUsecase := biz.NewSubscriptionUsecase(subscriptionRepo, paymentClient, logger)
	subscriptionService := service.NewSubscriptionService(subscriptionUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, subscriptionService, logger)
	httpServer := server.NewHTTPServer(bootstrap, subscriptionService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
