// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"xinyuan_tech/subscription-service/internal/biz"
	"xinyuan_tech/subscription-service/internal/conf"
	"xinyuan_tech/subscription-service/internal/data"
	"xinyuan_tech/subscription-service/internal/server"
	"xinyuan_tech/subscription-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(bootstrap)
	client := data.NewRedis(bootstrap)
	dataData, cleanup, err := data.NewData(bootstrap, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	planRepo := data.NewPlanRepo(dataData, logger)
	userSubscriptionRepo := data.NewUserSubscriptionRepo(dataData, logger)
	subscriptionOrderRepo := data.NewSubscriptionOrderRepo(dataData, logger)
	subscriptionHistoryRepo := data.NewSubscriptionHistoryRepo(dataData, logger)
	paymentClient, err := data.NewPaymentClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redsync := data.NewRedsync(client)
	subscriptionUsecase := biz.NewSubscriptionUsecase(planRepo, userSubscriptionRepo, subscriptionOrderRepo, subscriptionHistoryRepo, paymentClient, dataData, redsync, bootstrap, logger)
	subscriptionService := service.NewSubscriptionService(subscriptionUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, subscriptionService, logger)
	httpServer := server.NewHTTPServer(bootstrap, subscriptionService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
